### ISSUE TITLE
Allow @alexrobin and @kjano to review pulls to this repository

### ISSUE THREAD

**Issue by dr-shorthair** [w3c/sdw-sosa-ssn#102]
Also check @maximelefrancois86 if he wants to stay involved

**Comment by maximelefrancois86** [comment]
Yes, thanks, but I need to also join the WG I assume. 
Don't expect a high involvement from me, my bandwidth has reduced significantly with 👶

**Comment by rob-metalinkage** [comment]
@maximelefrancois86  happy to have you - great if you can supply any test cases as well we can use in regression tests to make sure we dont break anything, and to consider whether profiles can and should be defined for different valid implementation patterns,

**Comment by bert-github** [comment]
I invited @alexrobin to the repository with the possibility to review pull requests. @maximelefrancois86 and @kjano already had access.
