### ISSUE TITLE
Add `sosa:Observation` to the domain of `hasInput` 

### ISSUE THREAD

**Issue by dr-shorthair** [w3c/sdw-sosa-ssn#105]
Some 'Observations' use previously generated information as input, in addition to or instead of sensor stimuli. This particularly applies to 'observations' where the procedure is some complex processing or interpretation algorithm. 

`Observation` should be added to the `schema:domainIncludes` for `hasInput` to allow specific input values to be indicated, in addition to any general inputs indicated in the procedure description.

**Comment by dr-shorthair** [comment]
Or should it be renamed `hadInput` in this context?

**Comment by maximelefrancois86** [comment]
Good idea !
Then what about `hasOutput`? How would it relate to `hasResult`?

**Comment by maximelefrancois86** [comment]
> Or should it be renamed `hadInput` in this context?

I think this single-letter difference has the potential to generate great confusion among  users

**Comment by hylkevds** [comment]
There are two different uses of `hasInput`:
- The `hasInput` of the `Procedure` points to a _parameter description_.
- The `hasInput` of the `ProcedureExecution` must point to a _parameter value_ **and** to the _parameter description_ of the `hasInput` of the Procedure that this value is for.

These are different object properties, so using different names would be better. How about `hasInputValue` for the second one?
I suppose that for the second one we'll still need a class.

**Comment by dr-shorthair** [comment]
I agree.

**Comment by dr-shorthair** [comment]
#173 introduces `hasInputValue` and `hasOutputValue`

**Comment by dr-shorthair** [comment]
Closed by #173
