### ISSUE TITLE
Missing a class in SSN that generalize Observation/Actuation/Sampling

### ISSUE THREAD

**Issue by maximelefrancois86** [w3c/sdw-sosa-ssn#109]
In SSN there is ssn:Property that generalizes `sosa:ObservableProperty` and `sosa:ActuatableProperty`.
There is `ssn:System` that generalize `sosa:Sensor`, `sosa:Actuator`, `sosa:Sampler`.

It would be appropriate to have a class `ssn:ProcedureExecution` that generalizes `sosa:Observation`, `sosa:Actuation`, `sosa:Sampling`

**Comment by dr-shorthair** [comment]
Agree. 

(And in turn this might be a specialization of `prov:Activity`, or possibly an equivalent class?.)

**Comment by maximelefrancois86** [comment]
The alignment to `prov:Activity` is indeed what you proposed in the PROV Alignment Module (Sec. 6.5)

I wouldn't make the class `ssn:ProcedureExecution` equivalent to `prov:Activity` though.
The same way `sosa:Sensor`, `sosa:Actuator`, `sosa:Sampler` are only defined as sub-classes of `prov:Agent` and `prov:Entity`
`sosa:Procedure` is only defined as a sub-class of `prov:Plan`
and classes  `sosa:ObservableProperty` and `sosa:ActuatableProperty` are defined as sub-classes of `prov:Entity`
