### ISSUE TITLE
What feature of interest does a sensor observe ?

### ISSUE THREAD

**Issue by maximelefrancois86** [w3c/sdw-sosa-ssn#111]
When the "generic property" modeling choice is adopted (i.e., properties are generic to any feature of interest), then SOSA/SSN does not cover the following competency questions:

- we can model what property a sensor observes (sosa:observes), but what is the feature of interest it observes?
- we can model for what property an actuator is for (ssn:forProperty), but what is the feature of interest it acts on?
- we can model for what property a deployment is made (ssn:forProperty), but what is the feature of interest the deployment is made for?

Proposal: **introduce properties like `sosa:observesFeature`, `sosa:actsOnFeature`, `sosa:forFeature`**

**Comment by maximelefrancois86** [comment]
alternatively, we could extend the domain of `sosa:hasFeatureOfInterest` so that it contains `sosa:Sensor`, `sosa:Actuator`, `sosa:Deployment`, etc.

**Comment by dr-shorthair** [comment]
OK - you are proposing that SSN should support the description of the `Sensor`/`Actuator`/`Sampler` (and maybe the `Procedures` as well?). 
It could apply to both Feature-_types_ and individuals. 
 
I agree that this looks like a logical extension of the ontology. 
However, W3C requires evidence-of-implementation. 
Do you have this through SAREF (for example)?

**Comment by dr-shorthair** [comment]
Overtaken by #253
