### ISSUE TITLE
Introduction and Origins

### ISSUE THREAD

**Issue by dr-shorthair** [w3c/sdw-sosa-ssn#120]
The 2017 Rec doc has an origins/history section - https://www.w3.org/TR/vocab-ssn/#Developments 
For the update, this will need to be supplemented by some material around OMS and STA. 
@KathiSchleidt @sgrellet @alexrobin can you help?

**Comment by KathiSchleidt** [comment]
@dr-shorthair how to we best provide input to this text?

**Comment by dr-shorthair** [comment]
1. Create a branch
2. edit ssn/index.html
3. commit, push 
4. (when it is ready) issue a pull-request that **mentions this issue #120**

**Comment by KathiSchleidt** [comment]
@dr-shorthair thanks! I'm still lost in this repo, pointer to ssn/index.html was what I was missing!

**Comment by dr-shorthair** [comment]
@KathiSchleidt @sgrellet will you have time to look at this soon?

**Comment by dr-shorthair** [comment]
I'll take this on for now. 
I'll make 'Origins' a subsection of the Introduction.
