### ISSUE TITLE
Add STA alignment section in Rec doc

### ISSUE THREAD

**Issue by dr-shorthair** [w3c/sdw-sosa-ssn#122]
There is a section in the W3C/OGC recommendation/standard document that describes the alignments with other models and systems. 
Given the goal to increase alignment with STA and Connected Systems API, could we add a new section here @alexrobin (is Chris Tucker on GitHub?)

**Comment by sgrellet** [comment]
> Given the goal to increase alignment with STA

Would make sense to have https://github.com/hylkevds on this (well aware of our work on OMS <-> SOSA)

**Comment by KathiSchleidt** [comment]
@hylkevds can you access here?

**Comment by dr-shorthair** [comment]
Superseded by #147
