### ISSUE TITLE
Housekeeping branches

### ISSUE THREAD

**Issue by maximelefrancois86** [w3c/sdw-sosa-ssn#127]
`gh-pages` is the default branch .

I suggest we do some housekeeping by deleting branches that are far behind:

[bugs-and-nits](https://github.com/w3c/sdw-sosa-ssn/tree/bugs-and-nits) (38 commits behind)
[rjksmith](https://github.com/w3c/sdw-sosa-ssn/tree/rjksmith) (78 commits behind)
[original-pre-update](https://github.com/w3c/sdw-sosa-ssn/tree/original-pre-update)   (82 commits behind)
[main](https://github.com/w3c/sdw-sosa-ssn/tree/main)   (67 commits behind)

**Comment by dr-shorthair** [comment]
Yeah - `bugs-and-nits` may be reopened later, but should be relative the a current version of `gh-pages`. 
`original-pre-update` is a tag, so the branch can be removed. 
`main` can be removed. 
`rjksmith` seems to be related to the ogc-api work - @rjksmith @rob-metalinkage is this branch still useful.

**Comment by dr-shorthair** [comment]
old branches removed
