### ISSUE TITLE
Alignment of iso19156-om:OM_Observation.featureOfInterest with sosa:hasFeatureOfInterest

### ISSUE THREAD

**Issue by maximelefrancois86** [w3c/sdw-sosa-ssn#128]
This is a very minor issue:

In section 6.3.5 Property Alignments, alignment to OM, it is stated that:

 iso19156-om:OM_Observation.featureOfInterest	equivalent property  sosa:hasFeatureOfInterest

Actually sosa:hasFeatureOfInterest can also be applied to Actuations. And depending on the resolution of issue #111 , there may be even more classes that it will apply to.

I suggest to change this alignment as follows: 

 iso19156-om:OM_Observation.featureOfInterest	sub property of   sosa:hasFeatureOfInterest

And see if the same reasoning applies to other alignments.

**Comment by KathiSchleidt** [comment]
Related - in OMS we also have OMS:Sampling.featureOfInterest

**Comment by dr-shorthair** [comment]
Will we be keeping the O&M alignment in this version? See #121 
Since OMS = O&Mv3.0 the OMS alignment supersedes the O&M alignment. 

I propose to retire the O&Mv2.0 alignment from this edition.

**Comment by dr-shorthair** [comment]
The O&Mv2 alignment has been retired. 

The OMS alignment is summarized here: https://w3c.github.io/sdw-sosa-ssn/ssn/#OMS-Alignment-Property . There are several 1:n mappings. Each of these possibly implies a missing 'super-property' in OMS. 

However, there is no sub-property capability in UML. And it is a UML pattern that scopes property names to classes, even when the useful semantics don't differ. 

Nevertheless, it would be possible to define sub-properties in the sosa-oms: namespace, with the sub-property axioms living in the ssn-oms.ttl graph. 
e.g.
```
# in the SOSA-OMS graph

sosa-oms:observationHasFeatureOfInterest a owl:ObjectProperty .
sosa-oms:samplingHasFeatureOfInterest a owl:ObjectProperty .
sosa-oms:samplingHasFeatureOfInterest a owl:ObjectProperty .

# in the SSN-OMS graph

sosa-oms:observationHasFeatureOfInterest rdfs:subPropertyOf sosa:hasFeatureOfInterest .
sosa-oms:samplingHasFeatureOfInterest rdfs:subPropertyOf sosa:hasFeatureOfInterest .
sosa-oms:actuationHasFeatureOfInterest rdfs:subPropertyOf sosa:hasFeatureOfInterest .

```

and then use these in the alignment table. This is arguably more precise semantically, however it moves the SOSA-OMS alignment one step further away

What do you prefer?

**Comment by dr-shorthair** [comment]
O&Mv2 alignment has been retired
