### ISSUE TITLE
OMS req URI: om -> oms

### ISSUE THREAD

**Issue by KathiSchleidt** [w3c/sdw-sosa-ssn#131]
In the URIs linking to OMS requirements, the s is missing, should be:

http://www.opengis.net/spec/oms/3.0/req/...

**Comment by maximelefrancois86** [comment]
I don't think it is, I asked @dr-shorthair the other day.

It remains /om/, although the name of the spec changed in V3.

**Comment by sgrellet** [comment]
starting from http://www.opengis.net/spec/om/3.0/req/obs-cpt/Observation/validTime-sem
then checking in https://docs.ogc.org/as/20-082r4/20-082r4.html 
we only have 
Requirement : /req/obs-cpt/Observation/validTime-sem

I was trying to search in OGC def server but it does not help
@rob-metalinkage : can you help on this ?
what did you implement on the opengis.net/spec/ resolver ?

**Comment by dr-shorthair** [comment]
It is `http://www.opengis.net/spec/om/3.0/` 
See https://docs.ogc.org/as/20-082r4/20-082r4.html#_identifiers 

@KathiSchleidt does that confirm for you? 
If so, please close the issue.

**Comment by sgrellet** [comment]
my bad, I overlooked this during the session yesterday (even if we wrote that section ourselves !)

would be faster/safer to have all the rec and req already formatted this way all the way through the doc
=> @rob-metalinkage : is that feasible on OGC staff end ?

**Comment by dr-shorthair** [comment]
Closing
