### ISSUE TITLE
Move extra OMS terms into SOSA core

### ISSUE THREAD

**Issue by dr-shorthair** [w3c/sdw-sosa-ssn#132]
A number of new terms are defined in the [SOSA-OMS graph](https://github.com/w3c/sdw-sosa-ssn/blob/gh-pages/ssn/integrated/sosa-oms.ttl) to implement terms from OMS that are not currently in the SOSA core graph. 

Should any of these be added to SOSA core? 

- [x] [sosa-oms:SpatialSample](https://w3c.github.io/sdw-sosa-ssn/ssn/#OMSSpatialSample)
- [x] [sosa-oms:MaterialSample](https://w3c.github.io/sdw-sosa-ssn/ssn/#OMSMaterialSample)
- [x] [sosa-oms:StatisticalSample](https://w3c.github.io/sdw-sosa-ssn/ssn/#OMSStatisticalSample)
- [x] [sosa-oms:ObservingProcedure](https://w3c.github.io/sdw-sosa-ssn/ssn/#OMSObservingProcedure)
- [x] [sosa-oms:SamplingProcedure](https://w3c.github.io/sdw-sosa-ssn/ssn/#OMSSamplingProcedure)
- [x] [sosa-oms:PreparationProcedure](https://w3c.github.io/sdw-sosa-ssn/ssn/#OMSPreparationProcedure)
- [x] and for completeness [sosa-oms:ActuationProcedure](https://w3c.github.io/sdw-sosa-ssn/ssn/#OMSActuationProcedure)
- [ ] [sosa-oms:PreparationStep](https://w3c.github.io/sdw-sosa-ssn/ssn/#OMSPreparationStep)
- [ ] [sosa-oms:hasPreparationStep](https://w3c.github.io/sdw-sosa-ssn/ssn/#OMShasPreparationStep)
- [ ] [sosa-oms:madeOnPlatform](https://w3c.github.io/sdw-sosa-ssn/ssn/#OMSmadeOnPlatform)
- [ ] [sosa-oms:metadata](https://w3c.github.io/sdw-sosa-ssn/ssn/#OMSmetadata)
- [ ] [sosa-oms:observationType](https://w3c.github.io/sdw-sosa-ssn/ssn/#OMSobservationType)
- [ ] [sosa-oms:preparedSample](https://w3c.github.io/sdw-sosa-ssn/ssn/#OMSpreparedSample)
- [ ] [sosa-oms:processingDetails](https://w3c.github.io/sdw-sosa-ssn/ssn/#OMSprocessingDetails)
- [x] [sosa-oms:relatedObservation](https://w3c.github.io/sdw-sosa-ssn/ssn/#OMSrelatedObservation)
- [ ] [sosa-oms:relatedSampling](https://w3c.github.io/sdw-sosa-ssn/ssn/#OMSrelatedSampling)
- [x] [sosa-oms:resultQuality](https://w3c.github.io/sdw-sosa-ssn/ssn/#OMSresultQuality)
- [ ] [sosa-oms:samplePreparationStep](https://w3c.github.io/sdw-sosa-s8n/ssn/#OMSsamplePreparationStep)
- [ ] [sosa-oms:validTime](https://w3c.github.io/sdw-sosa-ssn/ssn/#OMSvalidTime)

**Comment by dr-shorthair** [comment]
Also `sosa:observationType` and `dqv:qualityMeasurement` (added in https://github.com/w3c/sdw-sosa-ssn/commit/97d928542acbc3f95deede70ffa118c797225633) 
- for `dqv:qualityMeasurement` it will just be the `schema:domainIncludes` annotation in sosa.ttl

**Comment by rob-metalinkage** [comment]
+1 for resultQuality  (have assumed this in an implementation activity)  - we should be looking for implementation for each if possible

**Comment by alexrobin** [comment]
I' m good with all the ones you have selected, that is:

[sosa-oms:SpatialSample](https://w3c.github.io/sdw-sosa-ssn/ssn/#OMSSpatialSample)
[sosa-oms:MaterialSample](https://w3c.github.io/sdw-sosa-ssn/ssn/#OMSMaterialSample)
[sosa-oms:StatisticalSample](https://w3c.github.io/sdw-sosa-ssn/ssn/#OMSStatisticalSample)

[sosa-oms:ObservingProcedure](https://w3c.github.io/sdw-sosa-ssn/ssn/#OMSObservingProcedure)
[sosa-oms:SamplingProcedure](https://w3c.github.io/sdw-sosa-ssn/ssn/#OMSSamplingProcedure)
[sosa-oms:PreparationProcedure](https://w3c.github.io/sdw-sosa-ssn/ssn/#OMSPreparationProcedure)
[sosa-oms:ActuationProcedure](https://w3c.github.io/sdw-sosa-ssn/ssn/#OMSActuationProcedure)

[sosa-oms:relatedObservation](https://w3c.github.io/sdw-sosa-ssn/ssn/#OMSrelatedObservation)
[sosa-oms:resultQuality](https://w3c.github.io/sdw-sosa-ssn/ssn/#OMSresultQuality)

**Comment by ldesousa** [comment]
I second @alexrobin's selection.

**Comment by dr-shorthair** [comment]
`ActuatingProcedure` is more consistent with `ObservingProcedure` and `SamplingProcedure`
