### ISSUE TITLE
Clarify relationship between  sosa-oms:resultQuality and ssn-system:qualityOfObservation

### ISSUE THREAD

**Issue by dr-shorthair** [w3c/sdw-sosa-ssn#138]
Need a stub for `dqv:hasQualityMeasurement` to support internal cross-references.

**Comment by dr-shorthair** [comment]
Resolve by putting links to all SOSA terms in mapping table

**Comment by dr-shorthair** [comment]
SOSA Update telecon 2023-12-14 resolved to define sosa-oms:resultQuality in place of dqv:hasQualityMeasurement

**Comment by dr-shorthair** [comment]
Today I noticed that [ssn-system:qualityOfObservation](https://w3c.github.io/sdw-sosa-ssn/ssn/#SSNSYSTEMqualityOfObservation) already exists. 
Should that be preferred to [sosa-oms:resultQuality](https://w3c.github.io/sdw-sosa-ssn/ssn/#OMSresultQuality)?

**Comment by dr-shorthair** [comment]
@sgrellet @KathiSchleidt @hylkevds any views on replacing [sosa-oms:resultQuality](https://w3c.github.io/sdw-sosa-ssn/ssn/#OMSresultQuality) with [ssn-system:qualityOfObservation](https://w3c.github.io/sdw-sosa-ssn/ssn/#SSNSYSTEMqualityOfObservation) ?

**Comment by dr-shorthair** [comment]
But note 
1. `ssn-system:` is non-normative
2. system quality might not be exactly the same as result quality? 

Can you comment on this @maximelefrancois86 ?

Do we need a [modelling pattern](https://w3c.github.io/sdw-sosa-ssn/ssn/#common-modeling-questions) for quality?

**Comment by rob-metalinkage** [comment]
Here is an example from a Survey use case (using JSON based on an implicit JSON-LD context)

```
{
          "type": "Feature",
          "geometry": null,
          "properties": {
            "hasFeatureOfInterest": "38471667",
            "resultTime": "2023-03-10T00:00:00Z",
            "hasResult": {
              "distance": 3.5,
              "angle": 283.96666666666664
            },
            "distanceType": "icsm-distance-type:ellipsoid",
            "hasResultQuality": {
              "distanceAccuracy": 0.0002292196,
              "distanceAccuracyClass": "nz-survey-class:A",
              "angleAccuracyClass": "nz-survey-class:A",
              "angleAccuracy": 0.061427230303
            },
            "angleType": "icsm-angle-type:bearing"
          }
        }
```

**Comment by dr-shorthair** [comment]
Ping @sgrellet @KathiSchleidt @hylkevds

**Comment by dr-shorthair** [comment]
Ping @sgrellet @KathiSchleidt @hylkevds again

**Comment by sgrellet** [comment]
In OMS [resultQuality](https://docs.ogc.org/as/20-082r4/20-082r4.html#_attribute_resultquality), is the same as in O&M appart that we softened the typing constraing from DQ_Element (ISO 19157) to Any.

Looking at previous working draft of vocab-ssn prior to the 2017 version (the current valid one), it seems to me that qualityOfObservation is equivalent to OMS resultQuality.

However, in https://www.w3.org/TR/vocab-ssn/ it is marked that it was moved to horizontal ontology module http://www.w3.org/ns/ssn/systems/ in the Change History (the text says "marked at risk" I don't what that imply).

I admit I'm not at ease understanding the consequences of having it in the System Capabilities Module : just a packaging artefact VS other more semantic consequences ?
I'll need more time / explanations to digest this

**Comment by KathiSchleidt** [comment]
I can confirm that [resultQuality](https://docs.ogc.org/as/20-082r4/20-082r4.html#_attribute_resultquality) is equivalent to [ssn-system:qualityOfObservation](https://w3c.github.io/sdw-sosa-ssn/ssn/#SSNSYSTEMqualityOfObservation)

As for implications of the placement in ssn-system, would need to better understand this.

Also more generally it's unclear to me why [ssn-system:qualityOfObservation](https://w3c.github.io/sdw-sosa-ssn/ssn/#SSNSYSTEMqualityOfObservation) is in ssn-system, everything else there pertains to Sytems, just the quality lost at the top. Maybe move to the core?
