### ISSUE TITLE
Add Datastream example to ObservationCollection proposal

### ISSUE THREAD

**Issue by lieberjosh** [w3c/sdw-sosa-ssn#14]

**Comment by dr-shorthair** [comment]
@alexrobin is this relevant to your concerns?

**Comment by dr-shorthair** [comment]
I believe that Datastream is a homogeneous-observation-collection, right?

**Comment by alexrobin** [comment]
@dr-shorthair Yes, Datastream is a concept used in both SensorML and the Connected Systems API. It is indeed an homogeneous observation collection.

**Comment by dr-shorthair** [comment]
This issue essentially duplicates #10 and #12
