### ISSUE TITLE
Re-draw figures - add new classes and properties

### ISSUE THREAD

**Issue by dr-shorthair** [w3c/sdw-sosa-ssn#140]
See figure captions marked 'TODO'

**Comment by dr-shorthair** [comment]
@maximelefrancois86 do you recall who did the diagrams in the 2017 edition? 
What tool did they use?

**Comment by maximelefrancois86** [comment]
@rgcmme did the diagrams. Probably using draw.io / diagrams.net
I don't have the sources of these diagrams.

**Comment by rgcmme** [comment]
Yes, I made the diagrams using Powerpoint.

The sources are already in the repo:

https://github.com/w3c/sdw-sosa-ssn/blob/gh-pages/ssn/SOSA-SSN%20ontologies%20v6.pptx

If I had to do them today I'd follow the Chowlk notation:

https://chowlk.linkeddata.es/

**Comment by dr-shorthair** [comment]
> If I had to do them today I'd follow the Chowlk notation:

It appears that Chowlk diagram --> TTL is supported, but not the other direction.
We have the TTL, we want diagrams. 
Or am I misunderstanding?

**Comment by rgcmme** [comment]
That's it, right now the only possible way is from diagram to OWL. I don't know of any tool that would make the opposite in a satisfactory way.

**Comment by dr-shorthair** [comment]
Guess I better learn draw.io

**Comment by dr-shorthair** [comment]
Potential replacement for Figure 1 - 
https://github.com/w3c/sdw-sosa-ssn/blob/183-clarify-ssn-ontology/ssn/images/SOSA-modules.png

![New Figure 1?](https://raw.githubusercontent.com/w3c/sdw-sosa-ssn/183-clarify-ssn-ontology/ssn/images/SOSA-modules.png)
