### ISSUE TITLE
Create SHACL implementation of 'SSN Module'

### ISSUE THREAD

**Issue by dr-shorthair** [w3c/sdw-sosa-ssn#142]
The SSN Module contains the axioms that relate SOSA classes and properties. 
For data validation there should be a SHACL implementation of the corresponding rules.

**Comment by dr-shorthair** [comment]
@rob-metalinkage @avillar could you create an issue in the relevant OGC repo, and then close this issue with a link to that.

**Comment by dr-shorthair** [comment]
Ping @rob-metalinkage @avillar

**Comment by avillar** [comment]
I've created [an issue in the ogcapi-sosa repository](https://github.com/opengeospatial/ogcapi-sosa/issues/4) to update the bblocks to the current draft, including the SHACL shapes.
