### ISSUE TITLE
SOSA-STA alignment

### ISSUE THREAD

**Issue by KathiSchleidt** [w3c/sdw-sosa-ssn#147]
Create a table parallel to the [OMS alignment](https://raw.githack.com/w3c/sdw-sosa-ssn/oms-alignment-links/ssn/index.html#OMS-Alignment-Class) for STA

**Comment by KathiSchleidt** [comment]
@hylkevds need support

**Comment by rob-metalinkage** [comment]
We can do some testing and implementation of these alignments using the "semantic uplift" capabilities of OGC BuildingBlock templates:  https://github.com/ogcincubator/iliad-apis-features/blob/master/README.md

The alignments occur in the JSON-LD context mappings from STA JSON schema to URIs,  and  SHACL rules to transform to canonical SOSA if required.  (other transformation languages such as SSSOM can be considered too)

**Comment by dr-shorthair** [comment]
Same as #122

**Comment by KathiSchleidt** [comment]
@dr-shorthair due to the merge of the PR, the link to the alignment table is no longer valid, and I'm too stupid to find in the repo - can you provide us a pointer where it went?

**Comment by dr-shorthair** [comment]
https://w3c.github.io/sdw-sosa-ssn/ssn/#OMS_alignment  

and 

https://github.com/w3c/sdw-sosa-ssn/blob/2b710f98bece66927cf05a22127ee7f3e48d2e7c/ssn/index.html#L5001

**Comment by KathiSchleidt** [comment]
@rob-metalinkage I'm looking at the URIs used to represent OMS reqs:

- obs-cpt: 	http://www.opengis.net/spec/om/3.0/req/obs-cpt/
- obs-core: 	http://www.opengis.net/spec/om/3.0/req/obs-core/
- sam-cpt: 	http://www.opengis.net/spec/om/3.0/req/sam-cpt/
- sam-basic: 	http://www.opengis.net/spec/om/3.0/req/sam-basic/

Will these become resolvable, or remain as placeholders?

**Comment by dr-shorthair** [comment]
Any chance of progress on this @hylkevds @KathiSchleidt

**Comment by rob-metalinkage** [comment]
We need the minimal graph to describe these things to provide a resource to resolve to. I'd rather that graph reference html resources, otherwise we'd need to maintain bespoke resolving rules for ever single specifications. We can have UI widgets to render the html from the graph.

**Comment by dr-shorthair** [comment]
@hylkevds @KathiSchleidt are there suitable anchors/URLs for x-refs into the STA specification?

**Comment by dr-shorthair** [comment]
In view of https://w3c.github.io/sdw-sosa-ssn/ssn/#OMS is this still needed?

**Comment by dr-shorthair** [comment]
OMS alignment is now an 'Extension' - https://w3c.github.io/sdw-sosa-ssn/ssn/#OMS 
Will there be a proposal for an explicit SSN/STA alignment?

**Comment by dr-shorthair** [comment]
@hylkevds @KathiSchleidt is bouncing though OMS to STA OK? 
STA/OMS alignment and models are unlikely to be complete in time. 

@rob-metalinkage briefly looked at STA/JSON implementation.  
STA is a more low-level implementation than SSN/SOSA. 
So the onus is on STA to document that STA is an implementation of SSN/SOSA, not this document.
(Are there things needed by STA that are missing in SSN/SOSA? )

Lack of formal language for expressing mappings between UML and RDF and JSON is a challenge here.

**Comment by sgrellet** [comment]
2024-12-04 webconf note : two options discussed
- A°/ map directly STA to SOSA
- B°/ defer this to SOSA <-mapping-> OMS <-mapping-> ST API

Parallel with activities going on the ‘metadata' world with DCAT <> ISO 19115 <> OGC API Records

Proposal to leave that exercise to SensorThings API <-> OMS: alignement exercise.

Consensus on this is an STA matter - since its more concrete and also as we already have the (normative) alignment between SOSA <-> OMS
