### ISSUE TITLE
Add `ogc:implements` to OGC ModSpec ontology

### ISSUE THREAD

**Issue by dr-shorthair** [w3c/sdw-sosa-ssn#149]
OGC ModSpec ontology is not currently normative or widely shared. 
The predicate `ogc:implements` has been proposed as an addition to the ontology, as it is required in the documentation of a mapping between an RDF implementation and elements of a UML-based OGC/ISO standard. 
It is used in Section 6 of the SOSA Update.

**Comment by rob-metalinkage** [comment]
this exists for the inverse direction, regarding the type of object

```
spec:StandardizationTargetType
  a owl:Class ;
  rdfs:label "Standardization target type" ;
.
spec:targetType
  a owl:ObjectProperty ;
  rdfs:domain spec:RequirementsClass ;
  rdfs:label "Standardization target type" ;
  rdfs:range spec:StandardizationTargetType ;
.
```

instances of implementations would be rdf:type spec:StandardizationTargetType - is this too strong?

would dct:conformsTo be sufficient - or perhaps a subProperty of this defining the nature of conformance?

**Comment by dr-shorthair** [comment]
`spec:StandardizationTargetType` 

1. it applies at the level of the _RequirementsClass_, not the individual _Requirement_
2. it says what _type_ of thing is being tested, not which _individual_

In this case `spec:StandardizationTargetType` is `owl:Ontology` I think (could also be **shapes graph**)

**Comment by dr-shorthair** [comment]
@rob-metalinkage @avillar could you create an issue in the relevant OGC repo, and then close this issue with a link to that.

**Comment by rob-metalinkage** [comment]
@dr-shorthair - OGC NA today was informed that OAB was taking on an update of the ModSpec - we should liaise and setup the relevant repository - at this stage we don't have one.

**Comment by rob-metalinkage** [comment]
added - as spec:implements using the ModSpec namespace prefix. 

This is the same URI as ogc-ms:  which may be clearer - so lets use this and consider modspec formalisation.
