### ISSUE TITLE
JSON-LD contexts

### ISSUE THREAD

**Issue by dr-shorthair** [w3c/sdw-sosa-ssn#150]
Need JSON-LD contexts (OGC building blocks) for 
- SOSA
- SOSA-OMS
- STA
- Connected Systems
- SAREF

**Comment by rob-metalinkage** [comment]
Contexts need to reference a JSON schema - this may be implicit elements based on ontology element names but not necessarily so.

A set of properties based on SOSA, and bound to GeoJSON schema is under development at https://github.com/opengeospatial/ogcapi-sosa

**Comment by dr-shorthair** [comment]
In particular see https://github.com/opengeospatial/ogcapi-sosa/blob/master/sosa-ssn.jsonld

**Comment by dr-shorthair** [comment]
@rob-metalinkage @avillar could you create an issue in the relevant OGC repo, and then close this issue with a link to that.

**Comment by rob-metalinkage** [comment]
see https://github.com/opengeospatial/ogcapi-sosa/issues/3
