### ISSUE TITLE
Long loading time for the SSN TR document

### ISSUE THREAD

**Issue by maximelefrancois86** [w3c/sdw-sosa-ssn#16]
Hi, 

This issue is not related to SDW, but rather to some Ajax call to https://www.w3.org/TR/tr-outdated-spec blocks the loading of the SSN spec, until this call finally fails because of a 404 error.

call is made in script `https://www.w3.org/scripts/TR/2016/fixup.js` at line 155. 

script `fixup.js` is loaded at the very end of the spec document.

**Comment by dr-shorthair** [comment]
Closing this - unreproducible
