### ISSUE TITLE
Specification of ProcedureExecution

### ISSUE THREAD

**Issue by dr-shorthair** [w3c/sdw-sosa-ssn#164]
Related #109 

While looking at #112 I'm pondering if `ProcedureExecution` is specified enough. 
Several of the properties of the subclasses `Observation` `Sampling` and `Actuation` are common to all (that's the point really) so  could/should be associated with `ProcedureExecution`. Probably with relaxed cardinalities. 

I suggest: 
- `sosa:usedProcedure only sosa:Procedure`
- `sosa:madeOnPlatform only sosa:Platform`
- `sosa:hasFeatureOfInterest only sosa:FeatureOfInterest`
- `sosa:hasUltimateFeatureOfInterest only sosa:FeatureOfInterest`
- `sosa:resultTime exactly 1 `

**Comment by hylkevds** [comment]
I think the ProcedureExecution should also have values for the inputs and outputs defined in the Procedure that it executes.

**Comment by dr-shorthair** [comment]
@hylkevds Could you propose concrete changes in https://github.com/w3c/sdw-sosa-ssn/tree/ProcedureExecution-spec
