### ISSUE TITLE
Cardinality of Actuation `actsOnProperty` and `hasResult` 

### ISSUE THREAD

**Issue by dr-shorthair** [w3c/sdw-sosa-ssn#174]
On Actuations, the cardinality of `actsOnProperty` and `hasResult` is &ge; 1. 
Compare with Observations where the cardinality of `observedProperty` and `hasResult` is = 1. 

When we were originally formulating the Observation model 20 years ago we considered it an important principle that each Observation concerned _one_ Property of _one_ FoI, and generated _one_ Result. If an application concerned complex values for any of these, then they should be encapsulated on the application side. In the general standard we did not want to get involved in implementation details, like how to map each element of a complex result to elements of a complex Observable Property, etc. That is up to the applications to manage. In the general standard we were primarily interested in standardizing the relationships and the overall shape. 

However, in the 2017 edition, somehow (I clearly wasn't paying attention) we broke that pattern on Actuation. 
@alexrobin pointed out that this is mentioned in the changelog -  item 10 in https://www.w3.org/TR/vocab-ssn/#changes-since-3rd-public-working-draft-https-www-w3-org-tr-2017-wd-vocab-ssn-20170504 
I'll go look back in the GitHub issue tracker to see if there is a specific record of the discussion. 
I'm seriously wondering if this might be something we can unpick now. 

Also see #112

**Comment by dr-shorthair** [comment]
Hmm. Looks like all the issues in the old repository tagged `ssn` were cleaned out. 

And I have not been able to track down when the Cardinalities were actually changed in the old repo.

**Comment by dr-shorthair** [comment]
I think I found the commit that changed the cardinalities: 
https://github.com/w3c/sdw/commit/882541f2b008d2935f6fb3e4becaa20901cd1e14#diff-bddd5642ff86775ffb333c45b693b0b76f4d23fbe90e3b20f4082c5dda6a8134 

16th April 2017, hidden in a large set of changes to the RDF files during a big refactor by Maxime.

**Comment by dr-shorthair** [comment]
Looks like I was responsible for multiple hasResults: https://lists.w3.org/Archives/Public/public-sdw-wg/2017Apr/0177.html 
I regret that. 

Can't find a record of where we agreed that actsOnProperty &ge; 1

**Comment by alexrobin** [comment]
+1 for setting cardinality of `actsOnProperty` to `EXACTLY 1` so it's consistent with the Observation model.

Yes, I also noticed the cardinality of `MIN 1` on `hasResult` (I was expecting `EXACTLY 1`) and was surprised about that too... Do you recall what was the use case for having multiple results?

**Comment by hylkevds** [comment]
Another +1 for changing it (back) to `EXACTLY 1`.
Does anyone know of common ontologies that would help users with multiplexing results?

**Comment by maximelefrancois86** [comment]
I don't, but collections of actuations may contribute to the answer

**Comment by dr-shorthair** [comment]
In 4c36cf4 I've 
- added ActuationCollection 
- adjusted hasResult and actsOnProperty to EXACTLY 1

**Comment by dr-shorthair** [comment]
PR #165

**Comment by dr-shorthair** [comment]
And included in superseding PR #178

**Comment by dr-shorthair** [comment]
Closed by #178
