### ISSUE TITLE
Document that vectorization of observed properties and result is accepted practice

### ISSUE THREAD

**Issue by alexrobin** [w3c/sdw-sosa-ssn#176]
As discussed in our last call, I would like this to be documented somewhere in an informative part of the document so that I can refer to it from Connected Systems.

**Comment by dr-shorthair** [comment]
Good point. How's this: 

https://raw.githack.com/w3c/sdw-sosa-ssn/complex-properties-results/ssn/index.html#SOSAObservation

https://raw.githack.com/w3c/sdw-sosa-ssn/complex-properties-results/ssn/index.html#SOSAActuation

**Comment by dr-shorthair** [comment]
Could also be added to the modeling patterns section.

**Comment by alexrobin** [comment]
I like it.
An alternative would be to consider these "vector" cases as small Observation/Actuation Collections. 

Now that we have the collection pattern allowing members of the collection to basically inherit anything defined at the collection level, this seems to be a special case of collections where everything is inherited except the observedProperty and the result value.

**Comment by alexrobin** [comment]
Sorry I just realized that the updated description in Observation and Actuation also refer to the collection pattern to handle these use cases, so I'm good.
