### ISSUE TITLE
Bring Procedure specializations into sosa namespace?

### ISSUE THREAD

**Issue by alexrobin** [w3c/sdw-sosa-ssn#177]
I don't find it logical that SOSA defines system specializations (i.e. `sosa:Sensor`, `sosa:Actuator`, `sosa:Sampler`), but not the equivalent procedure specializations that were introduced by OMS (i.e. `ObservingProcedure`, `SamplingProcedure`).

This is especially confusing since `ActuationProcedure` was also added to the `sosa-oms` namespace (probably inherited from my original PR) although it's NOT defined by OMS.

**Comment by dr-shorthair** [comment]
I agree, but this is a sub-issue of #132. 
Let's look at them all together.
