### ISSUE TITLE
Should resources in the `ssn-system` namespace also be merged into `sosa`?

### ISSUE THREAD

**Issue by alexrobin** [w3c/sdw-sosa-ssn#179]

**Comment by rob-metalinkage** [comment]
If we are formally aligning with OMS, then this should be a separate module, but could use the namespace - depends on exactly how we define intended scope of this namespace.

**Comment by dr-shorthair** [comment]
Discussed in 2024-02-01 telecon. 
1. As far as we know, this module still has not been widely implemented. 
2. The level of detail is (i) greater than the rest of SSN, yet (ii) still incomplete, and is likely to evolve rapidly if it gets used at all
3. The scope of this module really merits a separate governance arrangement, and therefore a separate namespace still makes sense. 

Conclusion is that we leave it as a non-normative module in its own namespace, and explore whether a separate governance arrangement could be found - e.g. OGC ConnectedSystems (@alexrobin), SAREF (@maximelefrancois86), ... 

I propose to close this with the decision 'no change'.

**Comment by alexrobin** [comment]
@dr-shorthair I'm ok with the 'no change' decision
