### ISSUE TITLE
Sample modeling in sosa/ssn

### ISSUE THREAD

**Issue by croussey** [w3c/sdw-sosa-ssn#19]
we try to reuse the sosa ontology  to design a contextual system about irrigation.
We notice in the sosa documentation that the class Sample is defined as a subClass of FeatureOfInterest... 
http://w3c.github.io/sdw/ssn/#SOSASample
not that in sosa ttl file Sample class is not defined as a subClass of FeatureOfInterest Class.

I found the subClassOf modeling very strange because the link between a sample and a featureOfinterest is a kind of partOf link...
The sample maybe a part of the feature of interest where the observation is made.. sample express that the feature of interest can not be taken as a whole to make an observation... It is really true about weather observation or soil observation
When the featureOfInterest is small I could understand that a sample is one of the instance of the featureOfInterest but it is not the case all the time.. 

The property to describe that a sample is part of a feature is isSampleOf (with the inverse hasSample). 

The main point is if  a sample may be linked to a featureOfInterest by a partOf relationship (isSampleOf) thus you should remove the subClassOf relationship between a FeatureOfInterest class and Sample class.
Is it possible to remove this information from the sosa documentation?

Best
Catherine Roussey
catherine.roussey@irstea.fr

**Comment by dr-shorthair** [comment]
Perhaps some of this discussion needs to be folded into the spec?

**Comment by dr-shorthair** [comment]
Check to see if the concerns here are reflected in the SSN Ontology documentation, in particular in 
- https://w3c.github.io/sdw-sosa-ssn/ssn/#SOSAhasFeatureOfInterest
- https://w3c.github.io/sdw-sosa-ssn/ssn/#SOSAhasUltimateFeatureOfInterest 
- https://w3c.github.io/sdw-sosa-ssn/ssn/#SOSASample 

and maybe also in 
- https://w3c.github.io/sdw-sosa-ssn/ssn/#common-modeling-questions

**Comment by ldesousa** [comment]
I came across this question while reviewing [PR #226](https://github.com/w3c/sdw-sosa-ssn/pull/226). From my experience with O&M and its offspring, I cannot really identify a context in which `Sample` would be a specialisation of `FeatureOfInterest`. My experience is primarily rooted on specimens: soil material, drinking and waste water, air. In none of the cases would a generalisation/specialisation apply.

Another aspect to consider is the current definition of `Sample`: "Samples are typically subsets or extracts from the feature of interest". Objectively something different from a sub-class or sub-type.

Finally, to my understanding there is no such generalisation in OMS. Some notes on the nature of `Sample` are found in [section 7.2.2.2](https://docs.ogc.org/as/20-082r4/20-082r4.html#_proximate_vs_ultimate_feature_of_interest). OMS also highlights the nature of `Sample` as the result of a `Sampling`. @KathiSchleidt or @hylkevds please correct me here.

I would advise two alternative courses of action:
1. Remove the generalisation from `Sample` to `FeatureOfInterest`. Note that in such case the user would still be able to define an instance as being of both types simultaneously, e.g. a specimen that is the subject of an `Observation` *a posteriori*. This is what I believe folk refer to as "FeatureOfInterest as a role".
2. Remake the current semantics of `Sample`, no longer defining it as sub-set or extract, but rather as a sub-type of `FeatureOfInterest`. Also clarify the role of `Sample` *vis à vis*  `Sampling`. In this case it would be necessary to thoroughly consider the alignment with OMS.

**Comment by KathiSchleidt** [comment]
@ldesousa I'm trying to understand your concerns.

It is correct that we do not specialize `Sample `from `FeatureOfInterest` in OMS as we don't have FeatureOfInterest in OMS, only featureOfInterest as an association role, see #232. If a feature is the target of an Observation, it automatically becomes a  `FeatureOfInterest`

I have no problem in removing the generalisation from `Sample `to `FeatureOfInterest` as any `Sample `on which we Observe automatically becomes a `FeatureOfInterest` through the act of Observation, you're option 1

**Comment by hylkevds** [comment]
From the point of view of OMS (and SensorThings):
Lets say there is a river. This river is a Feature.
I take a water sample from this River. This sample is also a Feature.
I measure the volume of the sample. In the context of this Observation, the sample is the ultimateFeatureOfInterest.
I measure the salinity of the sample. In the context of this Observation, the sample is the proximateFeatureOfInterest, while the river is the ultimateFeatureOfInterest.

**Comment by dr-shorthair** [comment]
This sub-class relationship goes back to discussions around the 2017 edition, where we first took Samples and Sampling seriously in the SSN context, and thus looked at its relationship with the terms already brought into SSN from SSNX. 

The argument was that every `Sample` was only created in order to support observations.  Therefore every Sample was expected to act as the `FeatureOfInterest` of an `Observation`, sooner or later. The sub-class relationship was asserted in anticipation of this. 

However, given the clarification proposed in https://raw.githack.com/w3c/sdw-sosa-ssn/232-domain-models-vs-feature-of-interest/ssn/index.html#model-domain we could reconsider this. 

@kjano @maximelefrancois86 @lieberjosh is there any backward compatibility concern if we removed this axiom from [ssn-sampling.ttl](https://github.com/w3c/sdw-sosa-ssn/blob/gh-pages/ssn/rdf/ontology/core/ssn-sampling.ttl)
```turtle
sosa:Sample rdfs:subClassOf sosa:FeatureOfInterest .
```
This change could be added to https://github.com/w3c/sdw-sosa-ssn/tree/232-domain-models-vs-feature-of-interest (preview link above) which is the subject of https://github.com/w3c/sdw-sosa-ssn/pull/236

**Comment by dr-shorthair** [comment]
Related to #232 for which a fix is proposed in #236

**Comment by croussey** [comment]
Maybe you could also modify the definition of sample. "Samples are typically subsets or extracts from the feature of interest of an observation." This sentence lets assume that the observation will be on the feature which will be different from the sample. I prefer the explanation that " every sample is expected to (eventually) be the feature-of-interest of a sosa:Observation". If there is a sample that means that the ultimate feature of interest can not be observed directly. Am I right?

**Comment by dr-shorthair** [comment]
Yes - the textual definition of Sample could be tightened up. 

> If there is a sample that means that the ultimate feature of interest cannot be observed directly. Am I right?

I would turn it around and say 'When the feature of interest cannot be observed directly, a sample of it might be used in Observations as a proxy for it. In such a case the Sample is the _proximate_ Feature of Interest of the Observation, while the Feature of Interest of the act of Sampling (i.e. the entity that the Sample 'isSampleOf') is the _ultimate_ Feature of Interest of the Observation.' (modulo tweaking the wording to allow for the fact that there may be a sequence of acts of sampling, so the ultimate FoI could be several steps removed) 

But I think we need to retain the idea that 'Samples are typically subsets or extracts from the feature of interest ... ' but _of the act of sampling_ that creates the sample. This really is quite important conceptually and is what allows us to have a common idea for material, spatial and statistical samples.

**Comment by dr-shorthair** [comment]
I've made these changes in https://github.com/w3c/sdw-sosa-ssn/pull/236/commits/1c4d709bb1f4b6d834b2afa8d262024249a93ba3

**Comment by ldesousa** [comment]
@dr-shorthair We just reviewed the commit collectively and thus decided to close the issue. Kanban updated accordingly.

**Comment by dr-shorthair** [comment]
Thanks @ldesousa 
I realised after the merge that I had not added an entry to the change log, and also a note in the text acknowledging the change in `sosa:Sample` axiomatization.

**Comment by dr-shorthair** [comment]
Documentation added.
