### ISSUE TITLE
Re-package SOSA into separate modules for Actuation, Observation, Sampling

### ISSUE THREAD

**Issue by dr-shorthair** [w3c/sdw-sosa-ssn#191]
Following on from discussion in #183 in particular https://github.com/w3c/sdw-sosa-ssn/issues/183#issuecomment-1913860023 
the 2024-02-01 telecon agreed to try re-packaging SOSA.

**Comment by dr-shorthair** [comment]
I have completed a refactoring of the RDF files following the modularization discussed in the last telecon. 
See here: https://github.com/w3c/sdw-sosa-ssn/tree/191-repackage-sosa-into-separate-modules/ssn/integrated 

Take a look in the following files:

- ~~sosa-core~~ [sosa-base.ttl](https://github.com/w3c/sdw-sosa-ssn/tree/191-repackage-sosa-into-separate-modules/ssn/integrated/sosa-base.ttl) - shared classes and properties, and (abstract?) superclasses
- [sosa-actuation.ttl](https://github.com/w3c/sdw-sosa-ssn/tree/191-repackage-sosa-into-separate-modules/ssn/integrated/sosa-actuation.ttl) - classes and properties for Actuation applications - imports ~~sosa-core~~ sosa-base
- [sosa-observation.ttl](https://github.com/w3c/sdw-sosa-ssn/tree/191-repackage-sosa-into-separate-modules/ssn/integrated/sosa-observation.ttl) - classes and properties for Observation applications - imports ~~sosa-core~~ sosa-base
- [sosa-sampling.ttl](https://github.com/w3c/sdw-sosa-ssn/tree/191-repackage-sosa-into-separate-modules/ssn/integrated/sosa-sampling.ttl) - classes and properties for Sampling applications -imports ~~sosa-core~~ sosa-base
- [sosa.ttl](https://github.com/w3c/sdw-sosa-ssn/tree/191-repackage-sosa-into-separate-modules/ssn/integrated/sosa.ttl) - all sosa classes and properties - imports sosa-actuation , sosa-observation , sosa-sampling

- [ssn-base.ttl](https://github.com/w3c/sdw-sosa-ssn/tree/191-repackage-sosa-into-separate-modules/ssn/integrated/ssn-base.ttl) - axiomatization of ~~sosa-core~~ sosa-base - imports ~~sosa-core~~ sosa-base
- [ssn-actuation.ttl](https://github.com/w3c/sdw-sosa-ssn/tree/191-repackage-sosa-into-separate-modules/ssn/integrated/ssn-actuation.ttl) - axiomatization of sosa-actuation - imports sosa-actuation 
- [ssn-observation.ttl](https://github.com/w3c/sdw-sosa-ssn/tree/191-repackage-sosa-into-separate-modules/ssn/integrated/ssn-observation.ttl) - axiomatization of sosa-observation - imports sosa-observation 
- [ssn-sampling.ttl](https://github.com/w3c/sdw-sosa-ssn/tree/191-repackage-sosa-into-separate-modules/ssn/integrated/ssn-sampling.ttl) - axiomatization of sosa-sampling - imports sosa-sampling 
- [ssn-deprecated.ttl](https://github.com/w3c/sdw-sosa-ssn/tree/191-repackage-sosa-into-separate-modules/ssn/integrated/ssn-deprecated.ttl) - terms in ssn: namespace from 2017 version that are now deprecated
- [ssn.ttl](https://github.com/w3c/sdw-sosa-ssn/tree/191-repackage-sosa-into-separate-modules/ssn/integrated/ssn.ttl) - all axiomatized classes and properties - imports ssn-actuation , ssn-observation , ssn-sampling , ssn-deprecated

The files sosa.ttl and ssn.ttl should provide the same as the old files with the same names, except that now it is necessary to follow more `owl:imports` paths. 

I think these are clean, but would be grateful of some more eyes looking over them. 

Now moving onto the HTML document.

**Comment by kjano** [comment]
Dear all,

if sosa is modularized into multiple files, would it make sense to also
have a sosa-features.ttl that would not only handle the FOI, ultimate FOI,
etc but also establish better bridges to GeoSPARQL and others?

Cheers,
Jano

**Comment by dr-shorthair** [comment]
I've refactored the HTML spec [/ssn/index.html](https://github.com/w3c/sdw-sosa-ssn/blob/191-repackage-sosa-into-separate-modules/ssn/index.html). 
Several of the document sections are in separate HTML fragments here: https://github.com/w3c/sdw-sosa-ssn/tree/191-repackage-sosa-into-separate-modules/ssn/frag 
There is a HTML fragment (i) for each module, (ii) for each alignment.
 
These get merged into the main document at run time. 
The main part of the document is now just a sequence of `data-include` directives - see https://github.com/w3c/sdw-sosa-ssn/blob/191-repackage-sosa-into-separate-modules/ssn/index.html#L562-L601 

You can preview the full thing here: 
https://raw.githack.com/w3c/sdw-sosa-ssn/191-repackage-sosa-into-separate-modules/ssn/index.html#Base

I haven't done much re-writing yet, just re-arranging and a lot of consistency checking - there were a lot of missing `domainIncludes` and `rangeIncludes` statements in the document, for example. 
I've rewritten some of the definitions in the HTML but have not yet transferred this back into the RDF. 

I'll now work outwards from this core, and plan to mostly re-write the introduction and various overviews ... unless you all think I'm barking up the wrong tree here.

**Comment by dr-shorthair** [comment]
> Dear all, if sosa is modularized into multiple files, would it make sense to also have a sosa-features.ttl that would not only handle the FOI, ultimate FOI, etc but also establish better bridges to GeoSPARQL and others? Cheers, Jano

The mechanics of that are much easier now I've done this work.  
Take a look at I've got to, and see if you can identify which terms can be safely/elegantly moved into another module. 

In the Core module I have tried to follow each class description with the properties that have than class in its `domainIncludes`. 
But I have not yet tidied up the other modules this way.

**Comment by dr-shorthair** [comment]
I have renamed sosa-core to sosa-base. 
This is because in the Rec. we refer to SOSA (as a whole) as the 'Core' of the SSN Ontology and I don't want to break that language. 

Note that I have not done anything with the figures yet, but here is an updated version of the package diagram with dependencies - 
![SSN modules](https://raw.githubusercontent.com/w3c/sdw-sosa-ssn/191-repackage-sosa-into-separate-modules/ssn/images/SSN-modules.png)

**Comment by dr-shorthair** [comment]
And here's what it could look like with the FoI and Properties factored out into yetanother module
![SSN modules with FoI](https://raw.githubusercontent.com/w3c/sdw-sosa-ssn/191-repackage-sosa-into-separate-modules/ssn/images/SSN%20package%20diagram.png)
