### ISSUE TITLE
Ontology Term URLS not accessible via HTTP(s)

### ISSUE THREAD

**Issue by oldskeptic** [w3c/sdw-sosa-ssn#195]
This ticket comes out of yesterday's teleconference about sosa/ssn namespaces and ontology availability.

**Problem**: Individual terms, eg: `https://www.w3.org/ns/sosa/host`, cannot be retrieved from the web server. 

In the beginning, ontologies tended to use `http://example.com/ontology#term` for individual terms. This follows html documents and when SPARQL servers / reasoners / curl / whatever try and retrieve a term, the URL fetches the entire ontology and the client parses the whole thing to find what it needs. It also means that a "naive" fetcher will always get all of the data that it needs, even if it can't differentiate `http://example.com/ontology` from `http://example.com/ontology#term`. This works on any web server in its default configuration because it always serves the same document by ignoring anchors; same as an html request. 

We now use an ontology URL hierarchy where the term `host` has URL `https://www.w3.org/ns/sosa/host` in an ontology with URL `https://www.w3.org/ns/sosa`. This is desirable since it allows clients to only retrieve the term of the ontology instead of retrieving ontologies the size of Western Europe every time. Currently OBO, schema.org and large open datasets work this way.

However most clients (eg: every client I know) are naive about this convention and will issue a `GET https://www.w3.org/ns/sosa/host` for the term which results in a 404 since the web server doesn't have that document. 

This is how the W3 Server is configured at the moment.

Short term solution: Configure URL rewriting on the W3C server according to the [W3C RDF... Working Group 2008](https://www.w3.org/TR/swbp-vocab-pub/#recipe3) with additional information from an old (2006) post of [Richard Cyganiak](http://richard.cyganiak.de/blog/2006/11/content-negotiation-with-hash-uris-long/).

Second alternative: Generate a separate file for every term in the ontology. It's an ugly solution but it works without changing the web server configuration.

Additional notes: `rdfs:isDefinedBy`  is suggested as a mechanism to recover the full ontology, but this is in RDFS space and not OWL space which relies on an explicit `owl:import` to the ontology URL. Also, its [rdfs definition](https://www.w3.org/TR/rdf12-schema/) reads as "_may be used to indicate an RDF vocabulary in which a resource is described_". While I think it is a good idea, it is not guaranteed to work.

**Comment by maximelefrancois86** [comment]
Hi,
What you're looking for is probably 
https://www.w3.org/ns/sosa/hosts
(There is a typo)
And I assure you the server is properly configured to redirect to the ontology file, or to the relevant section in the HTML documentation (at least in 2017 it was)

**Comment by oldskeptic** [comment]
> (There is a typo)    

I cut and pasted that from the document in front of me, so now I have to track that down. :/

However, content negotiation isn't working on `https://www.w3.org/ns/sosa`, I just get the raw turtle file instead of a redirect to the documentation.

**Comment by maximelefrancois86** [comment]
There deliberately isn't a redirection from the namespace to the HTML. 
We could decide to change that in the future, but my point is: 
The server has been configured with care, with the help of the W3C staff

**Comment by oldskeptic** [comment]
I agree that the server has been configured with care.
There was confusion about this point yesterday in the meeting.
Compounded by the host typo.

I request that there be a negotiated redirection from the namespace to the HTML for the ontology like there is for terms.

**Comment by oldskeptic** [comment]
@bert-github can I have help moving this forward?

**Comment by bert-github** [comment]
Until I find the first bug, I think it now works as you wanted:

- When you ask for the namespace URL https://www.w3.org/ns/sosa/ with a browser, you now get the spec.
- As before, when you ask for a term such as https://www.w3.org/ns/sosa/Sample with a browser, you get the spec, scrolled to that term.
- Also as before, those URLs in a client that does not prefer HTML, get you the Turtle file (or RDF/XML, if the client prefers that).

The same for the other namespaces in the SSN spec.

I found a method that respects the HTTP content negotiation algorithm. E.g., a client that sends

    Accept: text/turtle,text/html;q=0.1

now gets Turtle, where previously it got HTML, despite the low q-factor.

Disadvantage of returning the specification to browsers: The specification says at the start: ‘The SOSA ontology is available at http://www.w3.org/ns/sosa/’. But if you click on that link now, you just get the specification again, where previously you got the Turtle file.

At the next update of the spec, we should probably change that line to ‘… is available at http://www.w3.org/ns/sosa/sosa.ttl’. And in general, all links that are supposed to return RDF files should be changed to include the full filename.

I wrote some [documentation](https://www.w3.org/People/Bos/apache-ns-conneg) of the Apache configuration I came up with. It may be useful if people have other namespace URLs that should behave the same way.

**Comment by oldskeptic** [comment]
@bert-github works for me. Thank you for this!
