### ISSUE TITLE
Common modeling questions

### ISSUE THREAD

**Issue by dr-shorthair** [w3c/sdw-sosa-ssn#197]
The section 'Common modeling questions' presents some examples of usage which give guidance as to how to apply SSN in applications. 
However, it is problematic in a number of ways:
1. in some cases (e.g. UoM) several options are presented without a strong recommendation as to which one is preferred for interoperability
2. the patterns are just given as examples, and are not formalized as profiles, potentially validatable
3. the set of patterns only covers a small part of the scope of potential variation in SSN usage

Since SSN is quite an abstract ontology, guidance on usage for applications is important. 
However, the scale and scope of the section in the current document is woefully inadequate. 

Propose to revise this section as follows: 
1. add commentary reflecting the notes above
2. OGC to develop a register of SSN Profiles targetted at various applications
3. reword the document to give stronger guidance and recommendations for some specific patterns.

**Comment by oldskeptic** [comment]
> OGC to develop a register of SSN Profiles targetted at various applications
+1

**Comment by dr-shorthair** [comment]
Should we copy or adapt material from SSN-Ext - which motivated the addition of `hasUltimateFeatureOfInterest`, `hasOriginalSample`, `hasSampledFeature`, and `ObservationCollection`  - into the Common Modeling Questions section. 
i.e. most of section 3 here: https://www.w3.org/TR/vocab-ssn-ext/#overview
