### ISSUE TITLE
Articulate how sensorML Sensor models and parameters relate to SSN

### ISSUE THREAD

**Issue by rob-metalinkage** [w3c/sdw-sosa-ssn#20]
O&M has a concept observation procedures, and SensorML codifies a model for this :

"the procedure property within an Observation instance may reference a SensorML description of the measurement process" 

also

"As discussed in the Core Concepts, any process can have inputs, outputs, and parameters"

SSN does not make any reference to such "parameters" although some concepts such as capability are explicitly modelled. 

is this out of scope, an oversight, or a valid concern for an extension?

**Comment by dr-shorthair** [comment]
@alexrobin is there anything else that should be added to SSN here? 
Possibly in a Connected Systems alignment? 

Note that the OMS alignment includes some additional terms needed for the alignment but not in the `sosa:` namespace - https://w3c.github.io/sdw-sosa-ssn/ssn/#OMS-Alignment-New-Terms 
A Connected Systems alignment could use a similar approach.

**Comment by rob-metalinkage** [comment]
Superseded by Connected Systems specification work and subsequent alignments,
