### ISSUE TITLE
Repository structure and documentation

### ISSUE THREAD

**Issue by dr-shorthair** [w3c/sdw-sosa-ssn#205]
The SSN/SOSA GitHub repository is still a bit of a mess. 
The core RDF artefacts are in `/ssn/integrated` ...
There are not enough readme's

Propose to rearrange
- `/ssn/integrated` --> /ssn/rdf/core, /ssn/rdf/extensions, /ssn/rdf/alignments to match the labeling in the spec document
- rationalize examples and informative-examples
- add readme's everywhere ...

**Comment by sgrellet** [comment]
+1
