### ISSUE TITLE
Extend domains and ranges to "Kind" classes

### ISSUE THREAD

**Issue by maximelefrancois86** [w3c/sdw-sosa-ssn#211]
Related to #107 and #209, 

The "Kind" classes may be included in the domains or ranges of many object properties.

For Systems in sosa-common:

- implementedBy (range)
- implements (domain)
- hasSubSystem (domain and range)
- isHostedBy (domain)
- ~hasDeployment~ (should only apply to instances I believe)
- hosts (range)
- ~inDeployment~ (should only apply to instances I believe)
- ~deployedSystem~ (should only apply to instances I believe)

For Platforms in sosa:common: 

- isHostedOn (domain and range)
- hosts (domain and range)
- ~inDeployment~ (should only apply to instances I believe)
- ~deployedOnPlatform~ (should only apply to instances I believe)

For Platforms in sosa:observations

- ~relatedObservation~ (should only apply to instances I believe)

For Sensors in sosa:observations:

- observes (domain)
- isObservedBy (range)
- madeObservation (domain)
- madeBySensor (range)
- ~relatedObservation~ (should only apply to instances I believe)

...

**Comment by dr-shorthair** [comment]
PR?

**Comment by dr-shorthair** [comment]
We decided not to implement 'Kind' classes, but to use OWL class/individual pattern instead. 
See https://w3c.github.io/sdw-sosa-ssn/ssn/#SystemType
