### ISSUE TITLE
Extend domains and ranges to PropertyOfInterest 

### ISSUE THREAD

**Issue by maximelefrancois86** [w3c/sdw-sosa-ssn#212]
Related to #106 and #126 extend domains and ranges to the class "PropertyOfInterest"

Wherever class "Property", "ObservableProperty" or "ActuatableProperty" is included in the domain or range of an object property, it would be appropriate to also include "PropertyOfInterest"

**Comment by dr-shorthair** [comment]
Could you create a PR please?

**Comment by KathiSchleidt** [comment]
@dr-shorthair @maximelefrancois86 have we now lost `PropertyKind`?

How do we indicate that a `PropertyOfInterest `bound to an `FoI `is a specialization of a specific generic `Property`?

**Comment by maximelefrancois86** [comment]
We have indeed. `sosa:Property` is for the FoI-independent obsProp,   `sosa:PropertyOfInterest` is the the FoI-specific obsProp.  

As for the second question, it's answered in https://github.com/w3c/sdw-sosa-ssn/issues/252 : I would recommend   `sosa:hasPropertyKind`, following https://saref.etsi.org/patterns/core_properties

**Comment by dr-shorthair** [comment]
Superseded by #252 ?
