### ISSUE TITLE
Remove OWL cardinality restrictions

### ISSUE THREAD

**Issue by dr-shorthair** [w3c/sdw-sosa-ssn#216]
1. take the Ontology outside DL
2. raises various problems ... 
https://github.com/w3c/sdw-sosa-ssn/pull/206#issuecomment-2010877514
https://github.com/w3c/sdw-sosa-ssn/pull/209#issuecomment-2007293991 

probably more. 

Mostly I added them where I though they made sense, but cardinalities are probably better managed at the application level using SHACL, rather in the Ontology layer where they affect reasoning and can cause difficult-to-control inconsistencies.

**Comment by ldesousa** [comment]
I would like to follow on [the comment by @rgcmme](https://github.com/w3c/sdw-sosa-ssn/pull/206#issuecomment-2011390768). Constraints modelled alone at application level (e.g. with SHACL) would inevitably lead to misinterpretations of the ontology.

An example I am currently dealing with is the relation between Observation and Procedure. Can/should an observation refer to more than one procedure? In OMS the restriction is set by the class diagram itself, wheres in SOSA/SSN the `sosa:usedProcedure` object property has no cardinality indication. Therefore a SOSA observation with two different procedures is valid, whereas it is not so in OMS/STA.

I don't have the experience with reasoning to sense the troubles cardinalities could imply. Therefore I admit those difficulties to eventually prevent their specification, but in that case I would prefer to have them absent altogether.

**Comment by oldskeptic** [comment]
I would suggest leaving cardinality restrictions in SOSA. They are unlikely to break things on the reasoner side and if that's the SOSA design, that's what the ontology should say. 

OWL and SHACL tend to draw different people but this level of restriction isn't problematic IMHO.

**Comment by dr-shorthair** [comment]
I have found it necessary to remind people that OWL cardinality restrictions are _not_ validation constraints. 
The OWA still seems to be a step too far for some smart users. 

AFAICT the one that really matters crossing over from OWA to CWA is where cardinality=1 - that means that _if_ there is more than one, then _either_ they are identical _or_ there is an inconsistency. 

But I will close this issue now as no-one else wants to deprecate cardinalities.
