### ISSUE TITLE
Add inverse role for all properties in SOSA (SSN)

### ISSUE THREAD

**Issue by kjano** [w3c/sdw-sosa-ssn#218]
As discussed, it seems like we defined inverse properties for most but not all relationships in SOSA/SSN. It would be good to either explicitly define all inverse property names or make sure we know why we omitted some.

**Comment by dr-shorthair** [comment]
Inverse properties were only defined where there was a requirement or request. 
Do they need to be complete? Is this desirable?
 
There are 22 object-properties without inverses in the `sosa:` namespace (see below).  
Adding these would enlarge the vocabulary quite a bit. 

Prov-o explicitly minimised the number of inverse properties - https://www.w3.org/TR/prov-o/#inverse-names - though it 'reserved' the names for all the inverses. 
DCAT also includes a note about the 'missing' inverses - https://www.w3.org/TR/vocab-dcat-3/#inverse-properties . 

Perhaps we could just add a similar note in the SSN Ontology documentation? 

---
SOSA ObjectProperties without an inverse:
- [sosa:forProperty](https://w3c.github.io/sdw-sosa-ssn/ssn/#SOSAforProperty)
- [sosa:hasInput](https://w3c.github.io/sdw-sosa-ssn/ssn/#SOSAhasInput)
- [sosa:hasOutput](https://w3c.github.io/sdw-sosa-ssn/ssn/#SOSAhasOutut)
- [sosa:usedProcedure](https://w3c.github.io/sdw-sosa-ssn/ssn/#SOSAusedProcedure)
- [sosa:phenomenonTime](https://w3c.github.io/sdw-sosa-ssn/ssn/#SOSAphenomenonTime)
- [sosa:hasUltimateFeatureOfInterest](https://w3c.github.io/sdw-sosa-ssn/ssn/#SOSAhasUltimateFeatureOfInterest)
- [sosa:hasInputValue](https://w3c.github.io/sdw-sosa-ssn/ssn/#SOSAhasInputValue)
- [sosa:hasOutputValue](https://w3c.github.io/sdw-sosa-ssn/ssn/#SOSAhasOutputValue)
- [sosa:hasSubSystem](https://w3c.github.io/sdw-sosa-ssn/ssn/#SOSAhasSubSystem)
- [sosa:deployedAsset](https://w3c.github.io/sdw-sosa-ssn/ssn/#SOSAdeployedAsset) (super-property of [sosa:deployedSystem](https://w3c.github.io/sdw-sosa-ssn/ssn/#SOSAdeployedSystem) )
- [sosa:hasMember](https://w3c.github.io/sdw-sosa-ssn/ssn/#SOSAhasMember)
- [sosa:resultQuality](https://w3c.github.io/sdw-sosa-ssn/ssn/#SOSAresultQuality)
- [sosa:observedProperty](https://w3c.github.io/sdw-sosa-ssn/ssn/#SOSAobservedProperty)
- [sosa:relatedObservation](https://w3c.github.io/sdw-sosa-ssn/ssn/#SOSArelatedObservation) 
- [sosa:isProxyFor](https://w3c.github.io/sdw-sosa-ssn/ssn/#SOSAisProxyFor)
- [sosa:wasOriginatedBy](https://w3c.github.io/sdw-sosa-ssn/ssn/#SOSAwasOriginatedBy) 
- [sosa:detects](https://w3c.github.io/sdw-sosa-ssn/ssn/#SOSAdetects) 
- [sosa:isSampleOf](https://w3c.github.io/sdw-sosa-ssn/ssn/#SOSAisSampleOf)
- [sosa:hasOriginalSample](https://w3c.github.io/sdw-sosa-ssn/ssn/#SOSAhasOriginalSample)
- [sosa:hasSampledFeature](https://w3c.github.io/sdw-sosa-ssn/ssn/#SOSAhasSampledFeature)
- [sosa:isResultOfMadeBySampler](https://w3c.github.io/sdw-sosa-ssn/ssn/#SOSAisResultOfMadeBySampler)
- [sosa:isResultOfUsedProcedure](https://w3c.github.io/sdw-sosa-ssn/ssn/#SOSAisResultOfUsedProcedure)

**Comment by sgrellet** [comment]
Sounds like a good idea. 

I'd tend to be closer to the PROV-O note; I feel DCAT one rather short on the explanatation side.

**Comment by dr-shorthair** [comment]
OK - tabulation of recommended names for inverses in an appendix - 
See #228 and https://raw.githack.com/w3c/sdw-sosa-ssn/218-add-inverse-role-for-all-properties-in-sosa-ssn/ssn/index.html#inverse-properties 
The tabulation is similar to how it was done in PROV-O. 

Building this table also allowed a consistency check so I fixed up some domain/range inconsistencies in both the TTL and HTML

**Comment by KathiSchleidt** [comment]
I get the point that this does add a lot of additional inverse properties. At the same time, I do see use cases for quite a few of them. @dr-shorthair many thanks for this overview table!!!

Would a Solomonic approach be useful? Provide these additional inverse properties, but in an extension? This way, those who don't need them are not overburdened, while those who would like to use them can do so in an aligned manner.

**Comment by rob-metalinkage** [comment]
An extension that defines SHACL rules to infer them might be useful too. Particularly any transitive properties.

**Comment by dr-shorthair** [comment]
Creation of inverse roles for all properties of `Observation` supersedes some uses of the [relatedObservation](https://w3c.github.io/sdw-sosa-ssn/ssn/#SOSArelatedObservation) predicate that was added for the [OMS alignment](https://w3c.github.io/sdw-sosa-ssn/ssn/#OMS-alignment). 

Looking at the `relatedObservation` roles in the [OMS Conceptual Observation Schema](https://docs.ogc.org/as/20-082r4/20-082r4.html#_conceptual_observation_schema) and [OMS Conceptual Sample Schema](https://docs.ogc.org/as/20-082r4/20-082r4.html#_conceptual_sample_schema) they are implemented more specifically as follows 

- `ObservingProcedure` -- `usedForExecution` --> `Observation`
- `ObservableProperty` -- `wasObservedBy` --> `Observation`
- `Observer` (`Sensor`) -- `madeObservation` --> `Observation`
- `Sample` -- `isFeatureOfInterestOf` --> `Observation` 

SSN/SOSA has indirect relationships (property-chains) for the other cases as follows 
- `Deployment` -- `deployedSystem` --> `Sensor` -- `madeObservation` --> `Observation`
- `Platform` (Host) -- `hosts` --> `Sensor` -- `madeObservation` --> `Observation`

I'm reluctant to clutter SSN/SOSA with additional direct relationships mirroring these, however. 

So `relatedObservation` is only required for the relationships from the Executions (and their collections) to observations. A particular case that we already mentioned in the document is to [link an Actuation to an Observation used to verify the outcome](https://w3c.github.io/sdw-sosa-ssn/ssn/#SOSAActuation). 

So my feeling is that we should just limit the `domainIncludes` for `relatedObservation` to these latter cases, and update the OMS alignment table to reflect this. 

Optionally we could also make the specific cases above into `subPropertyOf` `relatedObservation`. It could make the alignment a bit easier to express formally, though that would probably make it harder for readers to understand.

**Comment by dr-shorthair** [comment]
Previews: 
https://raw.githack.com/w3c/sdw-sosa-ssn/218-add-inverse-role-for-all-properties-in-sosa-ssn/ssn/index.html#inverse-properties - new terms with asterisks

https://raw.githack.com/w3c/sdw-sosa-ssn/218-add-inverse-role-for-all-properties-in-sosa-ssn/ssn/index.html#OMS-Alignment-Property-OMS

**Comment by dr-shorthair** [comment]
It was agreed in the 2024-06-12 telecon that 
(i) we should proceed with a full set of inverse properties
(ii) the tabulation in the Appendix was useful
(iii) the adjustments to the OMS alignment were needed
(iv) the HTML documentation needs completing to reflect the additions to the Ontology. 

I think I have now executed those changes. 
See preview at https://raw.githack.com/w3c/sdw-sosa-ssn/218-add-inverse-role-for-all-properties-in-sosa-ssn/ssn/index.html

#228 is now ready for review and (I hope) merging. 
Please take a look.

**Comment by avillar** [comment]
I've added a prototype for sorting tables like we discussed today: https://raw.githack.com/w3c/sdw-sosa-ssn/218-with-sort/ssn/index.html#inverse-properties

Is this what you had in mind?
