### ISSUE TITLE
`madeExecution` `madeBySystem` super-properties used on `Execution`

### ISSUE THREAD

**Issue by dr-shorthair** [w3c/sdw-sosa-ssn#225]
There is an asymmetry between 
- `usedProcedure`, that links any instance of an `Execution` or sub-class to its `Procedure`, 

and 
- `madeByActuator` `madeBySensor` `madeBySampler` that links an instance of a specific `Execution` sub-class  (i.e. `Actuation` `Observation` `Sampling`) to an instance of the `System` subclass (i.e. `Actuator` `Sensor` `Sampler`) that made it. 

Should this be neatened up by introducing `madeBySystem` as the super-property? 
And `usedActuatingProcedure` `usedObservingProcedure` `usedSamplingProcedure` as sub-properties?

**Comment by maximelefrancois86** [comment]
+1 on this. Anything that improves homogeneity is desirable.
I expect there may be some objections to using subproperty axioms in SOSA, though.

**Comment by dr-shorthair** [comment]
As per precedent, the sub-property axioms would be in ssn.ttl, and not in sosa.ttl

**Comment by dr-shorthair** [comment]
`madeBySystem` and `madeExecution` are logical requirements to accompany https://github.com/w3c/sdw-sosa-ssn/pull/130

**Comment by dr-shorthair** [comment]
Terms in red are the proposed additions, classes in brown are changes we already introduced

![System-Execution-Procedure-specializations](https://github.com/w3c/sdw-sosa-ssn/assets/608303/773bea5e-7c6b-4f5c-b173-7ec4ce58ab21)

**Comment by dr-shorthair** [comment]
@alexrobin how do these proposals line up with Connected Systems?

**Comment by alexrobin** [comment]
Yes, but in fact we only use the equivalent of the super-properties `madeBySystem` and `usedProcedure` since the surrounding object provides the context.

**Comment by dr-shorthair** [comment]
Specific predicates `madeByActuator`/`madeActuation` , `madeBySensor`/`madeObservation` , `madeBySampler`/`madeSampling` must be retained for backward compatibility reasons. 

With the introduction of `Execution` I suggest that the pair `madeBySystem`/`madeExecution` should be added. 
These fill in some gaps in the [overview diagram for `Execution`](https://raw.githack.com/w3c/sdw-sosa-ssn/218-add-inverse-role-for-all-properties-in-sosa-ssn/ssn/index.html#fig-classes-and-relationships-related-to-execution-of-procedures-explanation-of-the-notation-used-in-class-diagrams), as shown. 

But I tend to agree that `usedActuatingProcedure` , `usedObservingProcedure` , `usedSamplingProcedure` may not be needed, and risk bloating the ontology. 
Of course the range of `usedProcedure` can be constrained by Restrictions on the specializations of `Execution` (i.e. `Actuation`, `Observation` , `Sampling`) in the 'SSN' graphs.

**Comment by dr-shorthair** [comment]
- We already agreed to add the classes with `Brown` names. 

- I suggest we add the `Red` predicates. 

- While they would make the ontology more homogeneous overall, I'm now of the opinion that the `Pink` predicates are not needed and would unnecessarily bloat the ontology. 

![System-Execution-Procedure-specializations](https://github.com/w3c/sdw-sosa-ssn/assets/608303/b04b8cf9-077c-4df3-8709-e4c3dbd04a9f)

**Comment by dr-shorthair** [comment]
@ldesousa seems to generally agree to limit the additional terms, in his [comment on the draft PR](https://github.com/w3c/sdw-sosa-ssn/pull/226#issuecomment-2122911262) which I quote here: 

> I don't see technical issues with this implementation (yet), but I would like to think a bit more on this from higher level of abstraction. The ontology is moving towards a set of four very similar graphs, centered on the four main classes:
>
> Execution
> Actuation
> Observation
> Sampling
> Those classes are well defined and understood, not only by those of us in the group, but also to users in general that may deal with concerned datasets in this context. However, the semantic nuances between the sub-classes of Procedure and Property are less evident, i.e.:
> 
> ActuatingProcedure
> ObservingProcedure
> SamplingProcedure
> ActuableProperty
> ObservableProperty
> SamplingProperty
> Are all those classes necessary? Do they all have a well defined and unique semantic definition?
> 
> Finally coming to the predicates: are they all semantically unique? Or is a single predicate object property between Execution > and Procedure enough to convey that relation in all sub-graphs? I would rather have a leaner ontology, with as many elements as possible at the Execution (abstract?) level, only to be specialised in case of objective semantic differences.
> 
> Thoughts?

**Comment by dr-shorthair** [comment]
I [responded](https://github.com/w3c/sdw-sosa-ssn/pull/226#issuecomment-2123631458):

Thanks @ldesousa - this is exactly the conversation we need.

The Ontology was highly specific with `Actuator`-`Actuation`, `Sensor`-`Observation`, `Sampler`-`Sampling` and specialized predicates to link them (`madeActuation`/`madeByActuator` etc), though Procedure was non-specific along with just one general predicate `usedProcedure`.

Now we have introduced a generalization Execution, and specializations `ActuatingProcedure`, `ObservingProcedure`, `SamplingProcedure` (note that `ActuatableProperty` and `ObservableProperty` were there before). The proposed predicates (in red above) are really just my chasing through the consequences.

---

Sorry I didn't make the diagram earlier.

Preview here: 
https://raw.githack.com/w3c/sdw-sosa-ssn/225-madebysystem/ssn/index.html#SOSAmadeBySystem

**Comment by dr-shorthair** [comment]
@oldskeptic [responded](https://github.com/w3c/sdw-sosa-ssn/pull/226#issuecomment-2220471496) 

>> Now we have introduced a generalization Execution, and specializations ActuatingProcedure, ObservingProcedure, SamplingProcedure (note that ActuatableProperty and ObservableProperty were there before). The proposed predicates (in red above) are really just my chasing through the consequences.
>
>Do we need the specializations ActuatingProcedure, ObservingProcedure, SamplingProcedure? Is there a material difference in these classes that wouldn't be covered by Procedure? A bit late for this question I realise.

**Comment by dr-shorthair** [comment]
I agree that we should re-visit the addition of ActuatingProcedure, ObservingProcedure, SamplingProcedure to SSN/SOSA. 
See #235

**Comment by dr-shorthair** [comment]
Removing ActuatingProcedure, ObservingProcedure, SamplingProcedure the proposed properties are these: 

![MadeBySystem-MadeExecution](https://github.com/user-attachments/assets/96042a58-7ffe-4ca6-a184-690367734a0b)

**Comment by hylkevds** [comment]
The only use that I can think of is that it is easier to ask "Give me all instances of ObservingProcedure" than the alternative if they are all just instances of "Procedure" and require looking at the relations to figure out what a given Procedure is.

**Comment by dr-shorthair** [comment]
Agreed in 2024-07-17 telecon to add these properties, but that the documentation should make clear (emphasize) that 
- classes `Execution` and `System`, 
- properties `madeBySystem`, `madeExecution`, `usedForExecution` 

are _abstract_ super-classes and super-properties, and should not be used directly. 
They are included in the ontology primarily to establish the patterns. 
Their concrete sub-classes and sub-properties should be used in implementations.

**Comment by dr-shorthair** [comment]
Preview:
1. [new diagram in overview for Execution](https://raw.githack.com/w3c/sdw-sosa-ssn/225-madebysystem/ssn/index.html#fig-overview-of-the-key-classes-and-properties-general-execution-pattern-explanation-of-the-notation-used-in-class-diagrams)
2. Scope note on `sosa:Execution` [explaining that it should be treated as 'abstract'](https://raw.githack.com/w3c/sdw-sosa-ssn/225-madebysystem/ssn/index.html#SOSAExecution) 
3. Scope note on `sosa:System` [explaining that it should be treated as 'abstract'](https://raw.githack.com/w3c/sdw-sosa-ssn/225-madebysystem/ssn/index.html#SOSASystem) 
4. [`sosa:madeBySystem`](https://raw.githack.com/w3c/sdw-sosa-ssn/225-madebysystem/ssn/index.html#SOSAmadeBySystem)
5. [`sosa:madeExecution`](https://raw.githack.com/w3c/sdw-sosa-ssn/225-madebysystem/ssn/index.html#SOSAmadeExecution)
