### ISSUE TITLE
Deprecate ObservableProperty, ActuatableProperty

### ISSUE THREAD

**Issue by dr-shorthair** [w3c/sdw-sosa-ssn#237]
Only `sosa:Property` is needed. 
No functional difference between the sub-classes. 
Legacy sub-class relationships in ssn-deprecated.ttl would preserve backward compatibility. 

See argument here: https://github.com/w3c/sdw-sosa-ssn/issues/235#issuecomment-2243218266

**Comment by dr-shorthair** [comment]
@alexrobin @KathiSchleidt @ldesousa any comment on this?

**Comment by ldesousa** [comment]
I am in favour of this change.

**Comment by dr-shorthair** [comment]
Kathi also agreed earlier
2024-09-25 telecon agreed with this.

**Comment by sgrellet** [comment]
fine with me as well

**Comment by alexrobin** [comment]
I support this as well

**Comment by dr-shorthair** [comment]
@alexrobin @sgrellet could you review https://github.com/w3c/sdw-sosa-ssn/pull/249 please?

**Comment by alexrobin** [comment]
The only thing I noticed is this part of the documentation of `Actuator` that I don't think is necessary anymore:
```
Restriction: sosa:forProperty ONLY sosa:Property
```

Same thing in the RDF:
```
sosa:Actuator 
  rdfs:subClassOf sosa:System ;
  rdfs:subClassOf [ a owl:Restriction ; owl:onProperty sosa:forProperty ; owl:allValuesFrom sosa:Property ] ;
```

However, should the `Actuator` class have a restriction on the new `actsOn` property though?

Otherwise, it looks good to me.

**Comment by dr-shorthair** [comment]
Right. That restriction is 'inherited' from the parent class `sosa:System`. 
Also missed similar on `sosa:Sensor`. 
Fixed now. 

@alexrobin @sgrellet could you approve review so it can be merged.
