### ISSUE TITLE
move validTime to sosa:

### ISSUE THREAD

**Issue by rob-metalinkage** [w3c/sdw-sosa-ssn#241]
validTime is defined in alignments:

https://github.com/w3c/sdw-sosa-ssn/blob/gh-pages/ssn/rdf/ontology/alignments/sosa-oms.ttl#L384

but referenced like any other time property in description of sosa:ObservationCollection which is in sosa: namespace here:

https://github.com/w3c/sdw-sosa-ssn/blob/gh-pages/ssn/rdf/ontology/core/sosa-observation.ttl#L65

Feels like it should just be promoted to sosa: namespace to reduce complexity. 

Note validTime is a property of an observation in SensorThings

https://github.com/w3c/sdw-sosa-ssn/blob/gh-pages/ssn/rdf/ontology/core/sosa-observation.ttl#L65

**Comment by dr-shorthair** [comment]
Yes, I spotted that when doing my consistency check in 
https://github.com/w3c/sdw-sosa-ssn/commit/5d06e85c172015dafd3347587890c2a3a4ff1f8c 

I think the solution is to clean up the diagrams and documentation elsewhere, not willy-nilly move alignment terms into the core.

**Comment by dr-shorthair** [comment]
SamplingCollection PR is now merged, with consistency improvements. 
`validTime` now only mentioned in OMS alignment. 

See https://w3c.github.io/sdw-sosa-ssn/ssn/ to verify.
