### ISSUE TITLE
Review prefix consistency in examples

### ISSUE THREAD

**Issue by rob-metalinkage** [w3c/sdw-sosa-ssn#246]
This is the list of prefixes I had to bind to validate the examples...

  ex: http://example.org/data/
  qudt: http://qudt.org/
  qudt-1-1: http://qudt.org/
  qunit: http://qudt.org/vocab/unit/
  rdfs: http://www.w3.org/2000/01/rdf-schema#
  xsd: http://www.w3.org/2001/XMLSchema#
  sh: http://www.w3.org/ns/shacl#
  owl: http://www.w3.org/2002/07/owl#
  sosa: http://www.w3.org/ns/sosa/
  ssn-system: http://www.w3.org/ns/ssn/systems/

many examples have these explicitly, but not all - I think we should be consistent - its not necessary to include any we put in a list of assumed bindings up front.

**Comment by dr-shorthair** [comment]
Working on it in https://github.com/w3c/sdw-sosa-ssn/tree/update-examples-2

**Comment by dr-shorthair** [comment]
See https://github.com/w3c/sdw-sosa-ssn/issues/271
