### ISSUE TITLE
Functional properties

### ISSUE THREAD

**Issue by dr-shorthair** [w3c/sdw-sosa-ssn#257]
A very few terms in our ontology are classified in the SSN (strongly axiomatized) modules as `owl:FunctionalProperty` (or `owl:InverseFuntionalProperty`). 
This implies that for any subject of such a property, there is at most one object (or for any object there is at most one subject). 

In at least one case this is wrong: a Sample can be `isSampleOf` more than one Feature of Interest: e.g. a twig can be a sample of a branch, a tree, a forest, an ecosystem, or a taxon. 
So this axiom is unhelpful: in the twig example it would entail that all these FoI's are the same thing! 

I propose to remove this. 

(note that this particular constraint is in the HTML but not the RDF/TTL)

We also have 
- an inverse-functional constraint on `isResultOf` which is arguably the wrong direction, but maybe should be removed
- a Functional constraint on `wasOriginatedBy` and `wasObservedBy`, which may be OK (these come from the sensor-stimulus part of the ontology which I don't think has been used much). 

Comments @kjano @maximelefrancois86 @alexrobin ?

**Comment by dr-shorthair** [comment]
Any comments on this @kjano @maximelefrancois86 @alexrobin @ldesousa ?

**Comment by dr-shorthair** [comment]
I believe that the only one of these that may be correct in intention is 
```
sosa:wasOriginatedBy a owl:ObjectProperty , owl:FunctionalProperty ;
  schema:domainIncludes sosa:Observation ;
  schema:rangeIncludes sosa:Stimulus ;
.
```

But in the absence of a guarded constraint axiomatically tying it to `sosa:Observation`, it is probably pointless.

**Comment by maximelefrancois86** [comment]
> In at least one case this is wrong: a Sample can be `isSampleOf` more than one Feature of Interest: e.g. a twig can be a sample of a branch, a tree, a forest, an ecosystem, or a taxon. So this axiom is unhelpful: in the twig example it would entail that all these FoI's are the same thing!
> 
> I propose to remove this.

agree

> * an inverse-functional constraint on `isResultOf` which is arguably the wrong direction, but maybe should be removed

What `sosa:isResultOf` being inverse-functional implies, is that:  a procedure execution has only one result. Nothing in the spec makes me believe there could be more than one, but there is no mention of the opposite neither.


> * a Functional constraint on `wasOriginatedBy` and `wasObservedBy`, which may be OK (these come from the sensor-stimulus part of the ontology which I don't think has been used much).

agree to deprecate/delete this part

**Comment by alexrobin** [comment]
@dr-shorthair I haven't looked at all cases but I agree that in most cases the use of `owl:FunctionalProperty` is too restrictive given how the SOSA/SSN ontology is currently setup.

**Comment by dr-shorthair** [comment]
>What sosa:isResultOf being inverse-functional implies, is that: a procedure execution has only one result. Nothing in the spec makes me believe there could be more than one, but there is no mention of the opposite neither.

Would this be better expressed by making `hasResult` Functional?

**Comment by dr-shorthair** [comment]
OK - I propose to remove all Functional/InverseFunctional designations except on `hasResult`. 

Preview https://raw.githack.com/w3c/sdw-sosa-ssn/257-functional-properties/ssn/index.html#SOSAhasResult
