### ISSUE TITLE
Rename XCollection classes to 'Collection of Xs`

### ISSUE THREAD

**Issue by dr-shorthair** [w3c/sdw-sosa-ssn#258]
Feedback from X-Domain meeting convened by CODATA/DDI: 

Generally find SSN model is very good and useful. 
Some confusion from some terminology, most of which can be resolved in discussion. 
But the one that keeps biting people are the classes `ObservationCollection`, `SampleCollection` - as the word 'collection' is interpreted as an action, not an aggregation. 
`CollectionOfSamples` and `CollectionOfObservations` (etc) would be better. 
`SetOfSamples` and `SetOfObservations` better still. 

While 'collection' is one of the classic OO patterns, the language is a bit hostile to some audiences. 
Of course class-names are not documentation and labels and definitions should also be considered. 
But changing these class names now would not cause any backward compatibility problems. 
 
And SOSA class names already vary from OMS in some other places (`Platform` vs Host, `Sensor` vs Observer).

**Comment by dr-shorthair** [comment]
Or maybe even `SetOfObservations`.

**Comment by sgrellet** [comment]
> Of course class-names are not documentation and labels and definitions should also be considered.

That would usually be my first take. But you're the one who was in contact with them thus trusting you on the need to rename.

I think we should keep the wording 'collection' somewhere in the class name.

I can live with the CollectionOfX pattern

**Comment by dr-shorthair** [comment]
@simonhodson99 @klehnert55 @IseultLynch will "CollectionOfSamples" and "CollectionOfObservations" suffice?

**Comment by simonhodson99** [comment]
I’m fine with that.

S.

**Comment by dr-shorthair** [comment]
Pushback from @rob-metalinkage on this, since there are several existing deployments e.g. BDR uses ObservationCollection, OGC APIs use "Collection" as noun ubiquitously. Changing the name might undermine evidence-of-implementation. 

This linguistic issue is rooted in the Latin origins ... 

2024-11-13 telecon argues to leave as is.
