### ISSUE TITLE
SSN Extensions not normative?

### ISSUE THREAD

**Issue by KathiSchleidt** [w3c/sdw-sosa-ssn#263]
I just noticed that [6. SSN Extensions](https://w3c.github.io/sdw-sosa-ssn/ssn/#Extensions) is non-normative, includes the OMS extension.  Do we want this?

**Comment by sgrellet** [comment]
isn't that non-normative until proof of implementation ?

**Comment by dr-shorthair** [comment]
This is labelled 'non-normative' at too high a level. Need to move these tags down to the term or module level.

**Comment by KathiSchleidt** [comment]
Knock-off question, which of the 3 subsections under 6 are normative vs. informative:
- OMS Extension Module
- System Capabilities Module
- Sample Relations Module

**Comment by dr-shorthair** [comment]
I think all are intended to be normative.

**Comment by sgrellet** [comment]
+1 on the intent.

Re, the process, for each subsection do we need to 'prove implementation' before they officially become normative ?
