### ISSUE TITLE
Allow hasResult on ObservationCollection

### ISSUE THREAD

**Issue by dr-shorthair** [w3c/sdw-sosa-ssn#28]
Mentioned in [s3.3](https://www.w3.org/TR/vocab-ssn-ext/#observation-collection)

A collection of observations which have the same _result_ may be of interest (e.g. a particular organism occurrence in Biodiversity surveys). The set of traps (spatial samples) where the observations were made would be interesting to map. 

So `hasResult` should be an option on `ObservationCollection` 

(Thanks @kathischleidt )

**Comment by rob-metalinkage** [comment]
Is this as modelled in OMS - please provide links, snippets diagrams etc when asking for an alignement.
