### ISSUE TITLE
sosa or sosa-ext for SOSA/SSN Extensions?

### ISSUE THREAD

**Issue by kjano** [w3c/sdw-sosa-ssn#30]
I am unsure whether it would not be better to change something like sosa:hasMember into a sosa-ext namespace to avoid confusion, also because they make use of different modeling practices such as RDF vs schema.org domains and ranges. I already got several questions about this. IMHO, your (wonderful) extensions should be in their own namespace and import SOSA. For instance, I got asked why sosa:hasMember is not in the ontology, and I had to explain that it is in another ontology altogether.

**Comment by dr-shorthair** [comment]
Classes and Properties related to Collections have been added to `sosa:` #134 
hasUltimateFeatureOfInterest hasOriginalSample hasSampledFeature were added to `sosa:` as part of the OMS alignment - see #116
