### ISSUE TITLE
Complex results and values of observedProperties

### ISSUE THREAD

**Issue by rob-metalinkage** [w3c/sdw-sosa-ssn#32]
It is possible to observe more than one property of a feature at the same time. This may be handled with complex results, but it is unclear how a complex result can be mapped to more than one observed property.

the text at https://www.w3.org/TR/vocab-ssn/#SOSAhasResult for hasResult is sufficient open to allow any possible implementation via the "representing the value associated with" wording

"Relation linking an Observation and a Sensor or Actuator and a Result, which contains a value representing the value associated with the observed Property."

if the one result contains values for more than one observable property of the FOI  then this restriction makes it impossible to make the associations:

sosa:observedProperty EXACTLY 1

the definition of ObservableProperty is quite loose however, so it could possible be implemented as a sequence of atomic RDF properties perhaps? 

At any rate, some guidance on this seems appropriate, as its quite hard to apply SOSA to existing Features that dont have the exact complex result containers, but observations need to bundle a range of results.  Possible a ObservationCollection is the only option, but a special type where the collection is a set of related results sharing a common observation event ?

**Comment by dr-shorthair** [comment]
See note clarifying that Observations concern a single observedProperty. 
Complex observedProperties shoudl be handled with ObservationCollections. 

See https://w3c.github.io/sdw-sosa-ssn/ssn/#SOSAObservation
