### ISSUE TITLE
Dead link: Section 6.3.1 "official OWL implementation of ISO 19156 (O&M)..."

### ISSUE THREAD

**Issue by F3RR3T** [w3c/sdw-sosa-ssn#34]
The link "official OWL implementation of ISO 19156 (O&M) maintained by the ISO/TC 211 Group on Ontology Management" points to:

 https://github.com/ISO-TC211/GOM/tree/master/isotc211_GOM_harmonizedOntology/19156/2011

But that is a 404.

**Comment by dr-shorthair** [comment]
Now that ISO 19156:2013 has been published, we need to verify that the anchors and the links are correct

**Comment by dr-shorthair** [comment]
Superseded by mapping to OMS
See #116 #139
