### ISSUE TITLE
iso 19156 URIs vs SSN/SOSA URIs

### ISSUE THREAD

**Issue by bertvannuffelen** [w3c/sdw-sosa-ssn#39]
Hi 

Is the URI 
http://def.isotc211.org/iso19156/2011/Observation#OM_Observation

equivalent with 
 http://www.w3.org/ns/sosa/Observation? 

If so it there are a mapping available somewhere, if not, what is the difference?

**Comment by rob-metalinkage** [comment]
To a certain extent this has been superceded by OMS decision to use the SOSA update as the canonical RDF representation vocabulary, and hence URIs. 

Requirements for back-references to ISO and conformance classes in OMS as annotations supercede this. See #57

propose this can be closed and a specific ISO annotation task raised as an issue.

**Comment by sgrellet** [comment]
Agreed

**Comment by dr-shorthair** [comment]
Closed by #116 and #119 #136 #139
