### ISSUE TITLE
How should we handle associations to specialized Procedure classes?

### ISSUE THREAD

**Issue by alexrobin** [w3c/sdw-sosa-ssn#44]
More specific procedure types are introduced by OMS: `SamplingProcedure`, `PreparationProcedure` and `ObservingProcedure`. I also went ahead and add `ActuationProcedure` for consistency.

There are no problems induced by adding the new classes per se. However, there are existing relationships/properties in many places that currently target the generic `Procedure` class while OMS uses the specialized class instead (e.g. an `Observation` or an `Observer` expects an `ObservingProcedure` and not any `Procedure`).

In PR w3c/sdw#1402 I made the choice of reinforcing the constraints on the existing properties to reflect this, but this is a breaking change compared to the existing version.

[Link to specific commit](https://github.com/w3c/sdw/pull/1402/commits/c13055f51c23a7105aba424f6303d1dd7f72be9d)

To avoid this breaking change, we may prefer keeping the existing properties with their looser constraint, and create separate sub-properties with a stricter constraint (e.g. `usedObservingProcedure` as a sub-property of `usedProcedure` with `ObservingProcedure` as its range, which could be used on `Observation` and `Observer` instead of the existing  generic `usedProcedure` property, etc.).

**Comment by dr-shorthair** [comment]
In this branch I've shifted the specialized procedure apparatus out to the OMS graph - 
see https://github.com/w3c/sdw-sosa-ssn/blob/OMS-mapping/ssn/mappings/sosa-oms-mapping.ttl#L173-L204 

([correct link below](https://github.com/w3c/sdw-sosa-ssn/issues/44#issuecomment-1778227166))

**Comment by lvdbrink** [comment]
> In this branch I've shifted the specialized procedure apparatus out to the OMS graph - see https://github.com/w3c/sdw-sosa-ssn/blob/OMS-mapping/ssn/mappings/sosa-oms-mapping.ttl#L173-L204

The link is broken...

**Comment by dr-shorthair** [comment]
https://github.com/w3c/sdw-sosa-ssn/blob/OMS-mapping/ssn/integrated/sosa-oms.ttl#L179-L210

**Comment by ldesousa** [comment]
@alexrobin Can this issue be closed? Or is there still something relevant? The PR was merged a while ago.

**Comment by alexrobin** [comment]
Yes, I believe this can be closed.
