### ISSUE TITLE
Investigate impact for any proposed breaking changes

### ISSUE THREAD

**Issue by alexrobin** [w3c/sdw-sosa-ssn#45]
We should probably try to figure out who would be impacted and ask their opinion.

**Comment by dr-shorthair** [comment]
I believe we agreed that there would be no breaking changes. Ae do not want to break existing implementations. 

Concerning the namespaces: even if classes and properties currently in `ssn:` get implemented in `sosa:` there will be no deletions from `ssn:`. Equivalence axioms can be used.

**Comment by dr-shorthair** [comment]
Given we decided not to make any incompatible changes, and there is a module for the deprecated terms that will still be loaded from the persistent ontology URI, is this issue still alive? 
@alexrobin can this be closed now?

**Comment by dr-shorthair** [comment]
Ping @alexrobin

**Comment by alexrobin** [comment]
Yes, I'm closing this since all changes are made in the spirit of not breaking things.
