### ISSUE TITLE
Muddled ObservableProperty 

### ISSUE THREAD

**Issue by KathiSchleidt** [w3c/sdw-sosa-ssn#49]
In some of the examples, the ObservableProperty includes the FoI of the Observation, e.g. "the height of tree w3c/sdw#124"
Adding "tree" to the height makes sense, but constraining this Property to Tree w3c/sdw#124 doesn't.

At a minimum, we should revisit the examples, maybe also provide better guidance.

**Comment by dr-shorthair** [comment]
@KathiSchleidt I think we can close this after @maximelefrancois86 work on `PropertyOfInterest` - right?

**Comment by KathiSchleidt** [comment]
Confirmed, #126 fixes this
