### ISSUE TITLE
Observation Collection

### ISSUE THREAD

**Issue by KathiSchleidt** [w3c/sdw-sosa-ssn#50]
As we've introduced `ObservationCollection` to OMS, we should shift this from SOSA EXT to core.

In addition, we may want to adjust the structure of the `ObservationCollection` to what we defined in OMS

**Comment by dr-shorthair** [comment]
Do we need _both_ homogeneous-X-collection and summarizing-X-collection, where X is either Observation or Sample? 
Also applies to #51

**Comment by dr-shorthair** [comment]
Also see #12

**Comment by dr-shorthair** [comment]
> In addition, we may want to adjust the structure of the ObservationCollection to what we defined in OMS 

@KathiSchleidt How does this differ from ssn-ext?

**Comment by dr-shorthair** [comment]
Ah - I now see the `type` attribute on ObservationCollection in OMS - see [my comment on #12](https://github.com/w3c/sdw-sosa-ssn/issues/12#issuecomment-1736637294). This is important. @KathiSchleidt I think this is the only real variation from SSN-Ext, right? 

But also see #95

**Comment by dr-shorthair** [comment]
I've temporarily factored `ObservationCollection` into a separate graph, to assist review - see  https://github.com/w3c/sdw-sosa-ssn/blob/collections/ssn/integrated/collections.ttl 

I also fixed some bugs in property cardinalities (@alexrobin I think you did a copy/paste from somewhere an didn't fix these)

Note that this does _not_ address 
(i) homogeneous vs summarizing collection - this would require different property cardinalities so I don't think a `type` attribute can resolve this
(ii) `hasResult` on `ObservationCollection` #28

**Comment by dr-shorthair** [comment]
In [SSN-ext](https://www.w3.org/TR/vocab-ssn-ext/#sosa:hasMember) the property linking an `ObservationCollection` to its member `Observations` or `ObservationCollections` was just `sosa:hasMember`. 

@alexrobin made separate properties for `SampleCollection` and `ObservationCollection`, called `memberSample` and `memberObservation`. 

1. This does not allow for member _collections_
2. is it really necessary to have more than one `member` property? Note that restrictions on the type of member can be managed using OWL Restrictions or SHACL rules that are scoped to the class. 

Also see #51 

I propose to revert to `sosa:hasMember` as originally described in [SSN-ext](https://www.w3.org/TR/vocab-ssn-ext/#sosa:hasMember)

**Comment by dr-shorthair** [comment]
See https://github.com/w3c/sdw-sosa-ssn/blob/collections/ssn/integrated/collections.ttl

**Comment by dr-shorthair** [comment]
- ~[Summarizing Observation Collection](https://github.com/w3c/sdw-sosa-ssn/blob/collections/ssn/integrated/collections.ttl#L213)~
- ~[Summarizing Sample Collection](https://github.com/w3c/sdw-sosa-ssn/blob/collections/ssn/integrated/collections.ttl#L101)~

now added to https://github.com/w3c/sdw-sosa-ssn/blob/collections/ssn/integrated/collections.ttl 

A couple of examples here: https://github.com/w3c/sdw-sosa-ssn/blob/collections/ssn/examples/02-homo-vs-summar-collection.ttl

**Comment by dr-shorthair** [comment]
I've remodeled this as follows: 

<img width="688" alt="image" src="https://github.com/w3c/sdw-sosa-ssn/assets/608303/992f4fc0-c693-4a11-ba63-1e02571a7764">

The properties of a general `(Observation|Sample)Collection` summarize the properties of its members. The general collection has a _list_ or _range_ of property values. This corresponds to OMS Summarizing collection. 

A `Homogeneous(Observation|Sample)Collection` has the cardinality of the properties limited to max=1, so all members have the same value for the property. This corresponds with OMS Homogeneous collection. 

I've updated the code to match. See https://github.com/w3c/sdw-sosa-ssn/blob/collections/ssn/integrated/collections.ttl and https://github.com/w3c/sdw-sosa-ssn/blob/collections/ssn/examples/02-homo-vs-summar-collection.ttl

**Comment by KathiSchleidt** [comment]
@dr-shorthair sorry for the silence, looks very good! :)

A few details are missing, but not sure necessary:
- validTime
- observationType
- resultQuality

**Comment by dr-shorthair** [comment]
`validTime` is defined in the SOSA-OMS graph. I'll add it to Collections with the additional `schema:domainIncludes`. 

`observationType` has not been implemented. I will add this to SOSA-OMS, then in due course we can consider if it needs to be moved to SOSA. 

Ditto `resultQuality`, though in this case I'm inclined to use [`dqv:hasQualityMeasurement`](https://www.w3.org/TR/vocab-dqv/#dqv:hasQualityMeasurement) rather than invent a new property.

See #119

**Comment by dr-shorthair** [comment]
See https://github.com/w3c/sdw-sosa-ssn/issues/124#issuecomment-1827025337

**Comment by dr-shorthair** [comment]
Documentation of Observation collections, with rules about 'inheritance' of property values from collections to members here 
https://raw.githack.com/w3c/sdw-sosa-ssn/collections/ssn/index.html#Collections

**Comment by dr-shorthair** [comment]
While writing the consistency rules for collection properties and member properties I'm coming around to thinking that a specific `HomogeneousObservationCollection` class is not needed. 
In practice it is merely the cardinality of the collection properties that defines the degree of homogeneity. 

- If any property is provided for the collection that has just a single value, then the members are homogeneous in that property. Members of the collection may omit that property and which may be inferred from the containing collection*. 
- If any property is repeated or has multiple or a range of values for the collection, then this summarizes the membership. Each member must have an explicit value for that property that falls within the range from the collection. 
- For any property _not_ provided for the collection, then the values on the members are unconstrained. 

*Of course, observations may be members of more than one collection, so the local information about any individual observation may vary depending on how it is packaged in collection(s). 

Having a special class where the properties mentioned are homogeneous (only one value for the collection), but any properties not mentioned are unconstrained, does not seem to actually gain anything. 

See https://raw.githack.com/w3c/sdw-sosa-ssn/collections/ssn/index.html#Collections-specification where I have tried to spell out the consistency rules. 

Thoughts? 

(Ditto `SampleCollection` #51)

**Comment by ldesousa** [comment]
@dr-shorthair This sounds more tidy indeed, and simplifies the ontology. Regarding the rules, not wanting to sound schizophrenic, it might be necessary to make it clear whether "property" refers to object property, data property, or both. The first paragraph only makes reference to "value", therefore implying data properties exclusively. But the second paragraph refers to range, thus implying object properties too.

**Comment by KathiSchleidt** [comment]
@hylkevds to me, Simon's simplification makes sense, but would like you to counter-check!

**Comment by dr-shorthair** [comment]
Updated consistency rules following today's meeting - see https://raw.githack.com/w3c/sdw-sosa-ssn/collections/ssn/index.html#Collections-specification 
(Don't fret about the broken links - they are in anticipation of some other PRs)
