### ISSUE TITLE
Sample Collection

### ISSUE THREAD

**Issue by KathiSchleidt** [w3c/sdw-sosa-ssn#51]
Parallel to the `ObservationCollection`, a `SampleCollection` would be valuable.

**Comment by dr-shorthair** [comment]
Do we need _both_ homogeneous-X-collection and summarizing-X-collection, where X is either Observation or Sample? 
Also applies to #50

**Comment by dr-shorthair** [comment]
Also see #36

**Comment by dr-shorthair** [comment]
@KellyVance [asked](https://github.com/w3c/sdw-sosa-ssn/issues/36#issuecomment-1691769002) 

@dr-shorthair a collection of samples would be a useful addition that would provide flexibility for how the GSQ is currently relating datasets.

In a similar line, is there a way to represent a sample that is composed of an aggregate of other samples.
e.g. Sample A has properties 1a 2a 3a, Sample B has properties 1b 2b 3b. The samples are merged into Sample AB for further/different observations.
The relationship doesn't appear to quite fit the description of isSampleOf. Is a new relationship class warranted?

**Comment by dr-shorthair** [comment]
@dr-shorthair [responded](https://github.com/w3c/sdw-sosa-ssn/issues/36#issuecomment-1691769008)

Maybe. I can imagine many many different potential relationship types.
In DCAT we managed this with a specific [dcat:Relationship class](https://www.w3.org/TR/vocab-dcat/#Class:Relationship), which is annotated with [dcat:hadRole](https://www.w3.org/TR/vocab-dcat/#Property:relationship_hadRole) whose value would be taken from a (controlled?) vocabulary - also see the [extended explanation](https://www.w3.org/TR/vocab-dcat/#UML-DCAT-Qualified-Relations). This pattern would probably work, right?

DCAT is primarily concerned with datasets, though this structure is tied to the general dcat:Resource which is 'any catalogued thing'. So it could be re-used directly, but since SSN/SOSA doesn't use anything else from the DCAT namespace, it might be better to add it natively (and maybe declare some kind of equivalence).

This probably merits a new issue.

**Comment by dr-shorthair** [comment]
This rdf graph contains a proposal for some sample-relations 
https://github.com/w3c/sdw-sosa-ssn/blob/main/ssn/rdf/sample-relations.ttl

**Comment by dr-shorthair** [comment]
@KathiSchleidt [wrote](https://github.com/w3c/sdw-sosa-ssn/issues/51#issuecomment-1691769751)
> I'd assumed SamplingCharacteristics, as Sampling provides all relevant information on how the Sample was created, thus best to guide the Collection

However, `SampleCollection` refers to a set of `Sampling` _results_ (endurants, continuants), and _not_ to a set of 'acts of `Sampling`' (perdurants, occurrents). So the `ObservationCollection` pattern does not strictly carry over. We need to look at the **Sample**Characteristics.

**Comment by dr-shorthair** [comment]
I've temporarily factored `SampleCollection` into a separate graph, to assist review - see  https://github.com/w3c/sdw-sosa-ssn/blob/collections/ssn/integrated/collections.ttl 

I also fixed some bugs in property cardinalities (@alexrobin I think you did a copy/paste from somewhere an didn't fix these)

Note that this does _not_ address 
(i) homogeneous vs summarizing collection - this would require different property cardinalities so I don't think a `type` attribute can resolve this

**Comment by dr-shorthair** [comment]
In [SSN-ext](https://www.w3.org/TR/vocab-ssn-ext/#sosa:hasMember) the property linking an `ObservationCollection` to its member `Observations` or `ObservationCollections` was just `sosa:hasMember`. 

@alexrobin made separate properties for `SampleCollection` and `ObservationCollection`, called `memberSample` and `memberObservation`. 

1. This does not allow for member _collections_
2. is it really necessary to have more than one `member` property? Note that restrictions on the type of member can be managed using OWL Restrictions or SHACL rules that are scoped to the class. 

Also see #50

I propose to revert to `sosa:hasMember` as originally described in [SSN-ext](https://www.w3.org/TR/vocab-ssn-ext/#sosa:hasMember)

**Comment by dr-shorthair** [comment]
See https://github.com/w3c/sdw-sosa-ssn/blob/collections/ssn/integrated/collections.ttl

**Comment by alexrobin** [comment]
@dr-shorthair Yep, I think using a single `hasMember` property for both is better.

**Comment by rob-metalinkage** [comment]
Agree.  


Note that when implementing an observation collection as a json FeatureCollection we uplift "features[]" as sosa:hasMember using @nest and this seems to work fine.  Having one property simplifies this as we don't need to create complex scoped contexts.

**Comment by dr-shorthair** [comment]
Documentation of Sample collections, with rules about 'inheritance' of property values from collections to members here
https://raw.githack.com/w3c/sdw-sosa-ssn/collections/ssn/index.html#SOSASampleCollection

Please check rules

**Comment by ldesousa** [comment]
> Documentation of Sample collections, with rules about 'inheritance' of property values from collections to members here https://raw.githack.com/w3c/sdw-sosa-ssn/collections/ssn/index.html#SOSASampleCollection
> 
> Please check rules

A few points:

1. Is a property defined for a Collection inherited by any member Sample? Or only if it is mentioned directly by the member? It might be necessary to make this explicit.
2. The IRI given for Sample Collection is `sosa:GeneralSampleCollection`, whereas for Harmonised Sample Collection is `sosa:SampleCollection`. Is this correct?
3. Took me some moments to understand what "The members of a general (summarizing) collection [...]" was referring to. Is it possible for the class names to match the IRIs?

Hope this makes sense.

**Comment by dr-shorthair** [comment]
While re-writing the consistency rules for collection properties and member properties I'm coming around to thinking that a specific `HomogeneousSampleCollection` class is not needed. 
In practice it is merely the cardinality of the collection properties that defines the degree of homogeneity. 

See discussion for `ObservationCollection` in [#50](https://github.com/w3c/sdw-sosa-ssn/issues/50#issuecomment-1833123191)

**Comment by KathiSchleidt** [comment]
What exactly are the properties on the SampleCollection? 
- Under ObservationCollection, this is clear (to me ;) ), all the classes associated with an Observation
- Under SampleCollection, this goes sideways as the core class associated to all the other classes describing the sample creation is the Sampling

Riffing on, SampleCollection is at the level of _ResultCollection_, while _SamplingCollection_ is at the level of ObservationCollection. 

The problem is that with Observations, we're happy to collect the Observations, not the Results, while with Samples, we'd prefer to collect the Samples, not the Samplings. However, I still get the feeling that the properties that describe the Sample (and thus the collection) are those from the Sampling.

**Comment by KathiSchleidt** [comment]
Based on the call, idea is to have the associations from both `Sample `and `Sampling `in the `SampleCollection`

**Comment by sgrellet** [comment]
+1 on the idea. That corresponds to what happens in the field.

**Comment by dr-shorthair** [comment]
Updated consistency rules following today's meeting - see https://raw.githack.com/w3c/sdw-sosa-ssn/collections/ssn/index.html#Collections-specification 
(Don't fret about the broken links - they are in anticipation of some other PRs)

Also added two Sampling properties to SampleCollection, as discussed
