### ISSUE TITLE
SOSA: handle issues with ssn or ssn-ext label?

### ISSUE THREAD

**Issue by KathiSchleidt** [w3c/sdw-sosa-ssn#53]
There's a pile of open issues labeled `ssn` or `ssn-ext` that we should also review while we do this update

**Comment by dr-shorthair** [comment]
The (ssn) tag was previously used primarily for issues in to the SSN module, which included 
- most of the axiomatization 
- a few of the classes and properties

I'm checking the tags on the open issues now.

**Comment by dr-shorthair** [comment]
@KathiSchleidt @sgrellet was all of ssn-ext subsumed into OMS? 
I am trying to simplify the tagging here - if we have the `sosa-oms-alignment` tag, can we get rid of the `ssn-ext` tag?

**Comment by dr-shorthair** [comment]
All the `ssn` and `ssn-ext` issues have been transferred over to here now, so I will close this
