### ISSUE TITLE
madeOnHost association bad english

### ISSUE THREAD

**Issue by KathiSchleidt** [w3c/sdw-sosa-ssn#55]
The naming `madeOnHost` is bad english, how about `madeFromHost` or `madeAtHost`? An `Observation` is made **ON** a FoI

**Comment by dr-shorthair** [comment]
Is `madeOnHost` from OMS, or from @alexrobin implementation?

**Comment by dr-shorthair** [comment]
I don't know where `madeOnHost` is. Not in any artefact in the current repo. 
@KathiSchleidt please clarify else close this issue.

**Comment by KathiSchleidt** [comment]
@dr-shorthair trust you that this is gone, thus won't trawl through and check
