### ISSUE TITLE
Range of `resultTime`

### ISSUE THREAD

**Issue by dr-shorthair** [w3c/sdw-sosa-ssn#98]
The range (expected value) of `sosa:resultTime` has always been an encoded date-time: `xsd:dateTime`. 
This is expressed in SOSA as
```
sosa:resultTime a owl:DatatypeProperty ;
  schema:domainIncludes sosa:Actuation ;
  schema:domainIncludes sosa:Observation ;
  schema:domainIncludes sosa:Sampling ;
  rdfs:range xsd:dateTime .
```
This is the _only_ property whose range is set using `rdfs:range`. 

For every other property the range expectation is set using `schema:rangeIncludes`, which is consistent with the weak axiomatization pattern agreed to for the SOSA graph. 
However, the expected range for [`schema:rangeIncludes`](https://schema.org/rangeIncludes) is a **Class** so this probably should not be used for `xsd:dateTime`. 

It is also effectively the only place in SOSA where a specific encoding instruction is introduced into what otherwise can be understood to be a 'conceptual model'. Encoding instructions may be better managed in a different layer - e.g. SHACL rules implementing specific _profiles_. 

I wonder if this axiom should be removed from the SOSA graph?

**Comment by edmondchuc** [comment]
This is related to https://github.com/w3c/sdw-sosa-ssn/issues/38.

**Comment by dr-shorthair** [comment]
Duplicate of #38
